// Gathers everything the update review needs: the new theme version (staged from GitHub, or a
// Hugo Module version fetched with `hugo mod get`), file changes, override drift, i18n keys,
// parameter changes and hooks that disappear.
import { api, type ModGetResult, type ThemeSource } from '../../../lib/api'
import { siteComponent, type ThemeComponent } from '../../../lib/themeSources'
import { loadTheme, mapLimit, readComponentI18n, readI18nFile, type ThemeData } from '../loadTheme'
import { mergeLayers } from '../merge'
import { findOverrides, OVERRIDE_ROOTS, type OverrideEntry } from '../overrides'
import { canonicalThemePath } from '../schema'
import { i18nFormat, i18nLanguage } from '../textOverrides'
import { compareHashes, hashComponent, type ThemeLock, type TreeDiff } from './lock'
import { lookupRepo } from './repoInfo'
import { classifyDrift, i18nDrift, lostHooks, paramDiff, paramsBecomingUnused, type Drift, type I18nDrift, type LostHook, type ParamDiff } from './plan'

export interface OverrideItem {
  entry: OverrideEntry
  /** Theme-relative path in the current and in the new version (null when absent). */
  basePath: string | null
  newPath: string | null
  siteText: string
  siteVersion: string
  baseText: string | null
  newText: string | null
  drift: Drift
  /** The theme file was edited locally, or there is no lock to tell. */
  baseUnverified: boolean
}

/** How the new version gets into place. */
export type UpdateMode =
  /** A copy under themes/: the staged folder replaces it. */
  | 'folder'
  /** A git submodule: `git checkout` of the new reference inside it. */
  | 'submodule'
  /** A Hugo Module: go.mod/go.sum already point at the new version (`hugo mod get`). */
  | 'module'

export interface ModuleChange {
  /** Module path given to `hugo mod get`. */
  path: string
  from: string
  to: string
  vendored: boolean
  goMod: ModGetResult
}

export interface UpdateReport {
  mode: UpdateMode
  /** GitHub source of a staged download (folder and submodule updates). */
  source: ThemeSource | null
  /** Commit of the downloaded version, when GitHub could be asked (null offline). */
  commit: string | null
  /** The reference moved while downloading: the commit may not match the files exactly. */
  commitApproximate: boolean
  /** Site-relative folder of the staged download (null for modules). */
  stagedRoot: string | null
  module: ModuleChange | null
  newTheme: ThemeData
  newHashes: Record<string, string>
  currentHashes: Record<string, string>
  files: TreeDiff
  /** Changes inside the theme folder since the lock was written (null without a lock). */
  localEdits: TreeDiff | null
  overrides: OverrideItem[]
  /** Site i18n keys whose theme text changed or disappeared. */
  i18n: I18nDrift[]
  params: ParamDiff
  unusedAfter: string[]
  lostHooks: LostHook[]
}

export interface PrepareInput {
  theme: ThemeData
  source: ThemeSource
  lock: ThemeLock | null
  siteParams: Record<string, unknown>
  siteTemplateKeys: Set<string>
  /** Site files generated by the app (not overrides). */
  ignore: string[]
  /** Commit the reference pointed to just before staging (null when unknown). */
  commitBefore?: string | null
  /** `submodule`: applied with git instead of replacing the folder. */
  mode?: 'folder' | 'submodule'
  /**
   * The current theme files are known to be unedited (a clean submodule checkout), so they are
   * a reliable merge base even without a lock.
   */
  trusted?: boolean
}

interface ReportCore {
  theme: ThemeData
  newTheme: ThemeData
  lock: ThemeLock | null
  trusted: boolean
  siteParams: Record<string, unknown>
  siteTemplateKeys: Set<string>
  ignore: string[]
}

/** Downloads the new version from GitHub into the staging folder and compares it. */
export async function prepareUpdate(input: PrepareInput): Promise<UpdateReport> {
  const { theme, source } = input
  const staged = await api.themeStageUpdate(source)
  // Resolve the reference again: if it moved during the download, the commit is approximate.
  let commit = input.commitBefore ?? null
  let commitApproximate = false
  if (commit) {
    const after = await lookupRepo(source.owner, source.repo, source.reference)
    if (after.ok && after.info.commit !== commit) {
      commit = after.info.commit
      commitApproximate = true
    }
  }
  const stagedRoot = staged.path.replace(/\\/g, '/').replace(/\/+$/, '')
  const newTheme = await loadTheme(theme.name, siteComponent(theme.name, stagedRoot))
  const core = await compareVersions({ ...input, newTheme, trusted: input.trusted ?? false })
  return { ...core, mode: input.mode ?? 'folder', source, commit, commitApproximate, stagedRoot, module: null }
}

export interface ModuleUpdateInput {
  theme: ThemeData
  /** The module after `hugo mod get` (from `hugo config mounts`, vendor folders ignored). */
  newComponent: ThemeComponent
  change: Omit<ModuleChange, 'to'> & { to?: string }
  siteParams: Record<string, unknown>
  siteTemplateKeys: Set<string>
  ignore: string[]
}

/**
 * Compares the module version the site used with the one `hugo mod get` fetched. Both live in
 * Hugo's module cache, which is never edited, so the old version is a reliable merge base.
 */
export async function prepareModuleUpdate(input: ModuleUpdateInput): Promise<UpdateReport> {
  const newTheme = await loadTheme(input.theme.name, input.newComponent)
  const core = await compareVersions({ ...input, newTheme, lock: null, trusted: true })
  const to = input.change.to ?? input.newComponent.module?.version ?? ''
  return { ...core, mode: 'module', source: null, commit: null, commitApproximate: false, stagedRoot: null, module: { ...input.change, to } }
}

async function readOrNull(component: ThemeComponent, path: string): Promise<string | null> {
  try {
    return (await component.read(path)).text
  } catch {
    return null
  }
}

async function compareVersions(input: ReportCore): Promise<Omit<UpdateReport, 'mode' | 'source' | 'commit' | 'commitApproximate' | 'stagedRoot' | 'module'>> {
  const { theme, newTheme, lock } = input
  const [current, next] = await Promise.all([hashComponent(theme.component), hashComponent(newTheme.component)])
  const currentHashes = current.hashes
  const newHashes = next.hashes
  const files = compareHashes(currentHashes, newHashes)
  const localEdits = lock ? compareHashes(lock.files, currentHashes, current.sizes) : null
  const edited = new Set([...(localEdits?.changed ?? []), ...(localEdits?.added ?? [])])

  const siteFiles = (await Promise.all(OVERRIDE_ROOTS.map((root) => api.listFiles(root).catch(() => [])))).flat().map((f) => f.path)
  const entries = findOverrides(siteFiles, theme.files, theme.label, input.ignore)
  const newByCanonical = new Map(newTheme.files.map((f) => [canonicalThemePath(f), f]))

  const overrides = (
    await mapLimit(
      entries.filter((e) => e.kind === 'override' && e.themeFile),
      4,
      async (entry): Promise<OverrideItem | null> => {
        const basePath = entry.themeFile!
        const newPath = newByCanonical.get(canonicalThemePath(basePath)) ?? null
        let site
        try {
          site = await api.readText(entry.sitePath)
        } catch {
          return null
        }
        const baseUnverified = !input.trusted && (!lock || edited.has(basePath))
        if (newPath === basePath && currentHashes[basePath] !== undefined && currentHashes[basePath] === newHashes[newPath]) {
          return { entry, basePath, newPath, siteText: site.text, siteVersion: site.version, baseText: null, newText: null, drift: { kind: 'unchanged' }, baseUnverified }
        }
        const [baseText, newText] = await Promise.all([readOrNull(theme.component, basePath), newPath ? readOrNull(newTheme.component, newPath) : Promise.resolve(null)])
        const baseReliable = input.trusted || !(lock && edited.has(basePath))
        const drift = classifyDrift({ base: baseText, theirs: newPath ? newText : null, ours: site.text, baseReliable })
        return { entry, basePath, newPath, siteText: site.text, siteVersion: site.version, baseText, newText, drift, baseUnverified }
      },
    )
  ).filter((o): o is OverrideItem => o !== null)

  const i18n = await i18nChanges(siteFiles, theme, newTheme)

  const before = mergeLayers({ schema: theme.match?.schema ?? null, scan: theme.scan, defaults: theme.defaults, siteParams: input.siteParams, siteTemplateKeys: input.siteTemplateKeys })
  const after = mergeLayers({ schema: newTheme.match?.schema ?? null, scan: newTheme.scan, defaults: newTheme.defaults, siteParams: input.siteParams, siteTemplateKeys: input.siteTemplateKeys })

  return {
    newTheme,
    newHashes,
    currentHashes,
    files,
    localEdits,
    overrides,
    i18n,
    params: paramDiff(theme.scan, newTheme.scan),
    unusedAfter: paramsBecomingUnused(before.unknown, after.unknown),
    lostHooks: lostHooks(entries, newTheme.files),
  }
}

/** The theme's i18n file for a language (any format; Hugo merges by language, not file name). */
function themeI18nFor(files: string[], language: string): string | null {
  return files.find((f) => /^i18n\/[^/]+$/.test(f) && i18nFormat(f) && i18nLanguage(f) === language) ?? null
}

/** Site i18n keys whose theme text changed or went away between the two versions. */
async function i18nChanges(siteFiles: string[], theme: ThemeData, newTheme: ThemeData): Promise<I18nDrift[]> {
  const sitePaths = siteFiles.filter((p) => /^i18n\/[^/]+$/.test(p) && i18nFormat(p))
  const out = await mapLimit(sitePaths, 4, async (sitePath): Promise<I18nDrift | null> => {
    const language = i18nLanguage(sitePath)
    const oldPath = themeI18nFor(theme.files, language)
    if (!oldPath) return null
    const newPath = themeI18nFor(newTheme.files, language)
    const [site, before, after] = await Promise.all([
      readI18nFile(sitePath),
      readComponentI18n(theme.component, oldPath),
      newPath ? readComponentI18n(newTheme.component, newPath) : Promise.resolve(null),
    ])
    // An unreadable new file is not a removal; a missing one is.
    if (!site || !before || (newPath && !after)) return null
    const drift = i18nDrift(sitePath, language, site.data, before.data, after?.data ?? null)
    return drift.changed.length + drift.removed.length > 0 ? drift : null
  })
  return out.filter((d): d is I18nDrift => d !== null)
}

/** Site params a newly installed theme would not use, for the theme gallery. */
export function unusedWith(newTheme: ThemeData, siteParams: Record<string, unknown>, siteTemplateKeys: Set<string>): string[] {
  return mergeLayers({ schema: newTheme.match?.schema ?? null, scan: newTheme.scan, defaults: newTheme.defaults, siteParams, siteTemplateKeys }).unknown
}
