import { useEffect, useState, type ReactNode } from 'react'
import { useTranslation } from 'react-i18next'

import { DiffView } from '../../../components/DiffView'
import { ErrorNote } from '../../../components/ErrorNote'
import { api, moduleApi, type GitSubmodule, type GoModTexts, type HugoModule, type HugoVersion, type SubmoduleStatus, type ThemeSource } from '../../../lib/api'
import { moduleComponent } from '../../../lib/themeSources'
import { ChangesDialog, type TextChange } from '../ChangesDialog'
import { versionAtLeast } from '../discovery'
import type { ThemeData } from '../loadTheme'
import type { I18nValue } from '../textOverrides'
import { compareHashes, hashComponent, inferSource, LOCK_PATH, lockText, makeLock, parseGithubRepo, parseLock, type ThemeLock, type TreeDiff } from './lock'
import { hasConflictMarkers } from './merge3'
import { defaultAction, type I18nDrift, type OverrideAction } from './plan'
import { prepareModuleUpdate, prepareUpdate, type OverrideItem, type UpdateReport } from './prepare'
import { githubModule, lookupRepo, moduleTags, shortSha, useRepoTags } from './repoInfo'

interface Props {
  theme: ThemeData
  siteParams: Record<string, unknown>
  siteTemplateKeys: Set<string>
  hugoVersion: HugoVersion | null
  /** Site files generated by the app (not overrides). */
  ignore: string[]
  onUpdated(): void
}

/** How this theme is installed, which decides how it is updated. */
type Mode =
  /** A copy under themes/ (downloaded archive): replaced by the staged version. */
  | { kind: 'folder' }
  /** A git submodule: staged for review, applied with `git checkout`. */
  | { kind: 'submodule'; submodule: GitSubmodule; status: SubmoduleStatus | null }
  /** A Hugo Module with a version in go.mod: `hugo mod get`. */
  | { kind: 'module'; module: HugoModule }
  /** A module replaced by a local folder: updated wherever that folder comes from. */
  | { kind: 'replaced'; module: HugoModule }
  /** Anywhere else (a custom themesDir…): not updatable here. */
  | { kind: 'other' }

async function listSubmodules(): Promise<GitSubmodule[]> {
  try {
    return await moduleApi.submodules()
  } catch {
    return []
  }
}

async function detectMode(theme: ThemeData): Promise<Mode> {
  const module = theme.component.module
  if (module && module.version) return { kind: 'module', module }
  if (module && theme.component.location === 'module') return { kind: 'replaced', module }
  if (theme.component.location === 'site') {
    const submodule = (await listSubmodules()).find((s) => s.path === theme.root)
    if (submodule) {
      const status = await moduleApi.submoduleStatus(submodule.path).catch(() => null)
      return { kind: 'submodule', submodule, status }
    }
    if (theme.root === `themes/${theme.name}`) return { kind: 'folder' }
  }
  return { kind: 'other' }
}

export function UpdatePanel(props: Props) {
  const { t } = useTranslation()
  const { theme } = props
  const [mode, setMode] = useState<{ name: string; mode: Mode } | null>(null)
  const [modeReload, setModeReload] = useState(0)

  // Detected again after an update; the previous answer stays on screen meanwhile, so the
  // panel (and what it just reported) is not torn down.
  useEffect(() => {
    let cancelled = false
    void detectMode(theme).then((found) => {
      if (!cancelled) setMode({ name: theme.name, mode: found })
    })
    return () => {
      cancelled = true
    }
  }, [theme, modeReload])

  if (!mode || mode.name !== theme.name) return <p className="text-sm text-zinc-500">{t('common.loading')}</p>
  const current = mode.mode
  if (current.kind === 'module') return <ModuleUpdate {...props} module={current.module} />
  if (current.kind === 'replaced') {
    return (
      <div className="space-y-3">
        <p className="text-sm text-zinc-600 dark:text-zinc-400">{t('theme.update.intro')}</p>
        <p className="rounded-md border border-amber-300 bg-amber-50 p-2 text-sm text-amber-900 dark:border-amber-800 dark:bg-amber-950 dark:text-amber-100">
          {t('theme.update.replaced', { dir: current.module.dir })}
        </p>
      </div>
    )
  }
  return <FolderUpdate {...props} mode={current} onModeChanged={() => setModeReload((n) => n + 1)} />
}

type LockState = { lock: ThemeLock | null; text: string | null; version: string | null }

function Notice({ children }: { children: ReactNode }) {
  return <p className="rounded-md border border-amber-300 bg-amber-50 p-2 text-sm text-amber-900 dark:border-amber-800 dark:bg-amber-950 dark:text-amber-100">{children}</p>
}

/** Themes copied under themes/ or checked out as git submodules: staged from GitHub, then applied. */
function FolderUpdate({ theme, siteParams, siteTemplateKeys, hugoVersion, ignore, onUpdated, mode, onModeChanged }: Props & { mode: Mode; onModeChanged(): void }) {
  const { t } = useTranslation()
  const [lockState, setLockState] = useState<LockState | null>(null)
  const [reloadKey, setReloadKey] = useState(0)
  const [localEdits, setLocalEdits] = useState<TreeDiff | null>(null)
  const [repo, setRepo] = useState('')
  const [reference, setReference] = useState('')
  const [busy, setBusy] = useState<'lock' | 'stage' | 'apply' | null>(null)
  const [error, setError] = useState<unknown>(null)
  const [lockChange, setLockChange] = useState<TextChange | null>(null)
  const [report, setReport] = useState<UpdateReport | null>(null)
  const [done, setDone] = useState<{ submodule: SubmoduleStatus | null } | null>(null)
  const [upToDate, setUpToDate] = useState<string | null>(null)
  const [offline, setOffline] = useState(false)
  const parsed = parseGithubRepo(repo)
  const repoTags = useRepoTags(parsed)
  const submodule = mode.kind === 'submodule' ? mode : null
  const submoduleBlocked = submodule !== null && (!submodule.status?.initialized || (submodule.status?.changes.length ?? 0) > 0)
  const updatable = (mode.kind === 'folder' || mode.kind === 'submodule') && !submoduleBlocked

  useEffect(() => {
    let cancelled = false
    void (async () => {
      const file = await api.readText(LOCK_PATH).catch(() => null)
      const lock = file ? parseLock(file.text) : null
      const usable = lock && lock.theme === theme.name ? lock : null
      if (cancelled) return
      setLockState({ lock: usable, text: file?.text ?? null, version: file?.version ?? null })
      const fromSubmodule = submodule ? parseGithubRepo(submodule.submodule.url) : null
      const inferred = usable?.source ?? fromSubmodule ?? inferSource(theme.themeToml?.values ?? null, theme.modulePath)
      setRepo(inferred ? `https://github.com/${inferred.owner}/${inferred.repo}` : '')
      setReference(usable?.source.reference ?? submodule?.submodule.branch ?? '')
      if (usable) {
        const current = await hashComponent(theme.component).catch(() => null)
        if (!cancelled && current) setLocalEdits(compareHashes(usable.files, current.hashes, current.sizes))
      }
    })()
    return () => {
      cancelled = true
    }
  }, [theme.root, theme.name, theme.component, theme.themeToml, theme.modulePath, submodule, reloadKey])

  if (!lockState) return <p className="text-sm text-zinc-500">{t('common.loading')}</p>
  const source: ThemeSource | null = parsed ? { ...parsed, name: theme.name, ...(reference.trim() ? { reference: reference.trim() } : {}) } : null

  async function createLock() {
    if (!source || !lockState) return
    setBusy('lock')
    setError(null)
    try {
      const { hashes } = await hashComponent(theme.component)
      setLockChange({ path: LOCK_PATH, before: lockState.text, after: lockText(makeLock(theme.name, source, hashes)), version: lockState.version })
    } catch (e) {
      setError(e)
    } finally {
      setBusy(null)
    }
  }

  async function check(force: boolean) {
    if (!source || !lockState) return
    setBusy('stage')
    setError(null)
    setDone(null)
    setUpToDate(null)
    try {
      // Which commit the reference points to now; offline this is skipped and the files decide.
      const lookup = await lookupRepo(source.owner, source.repo, source.reference)
      setOffline(!lookup.ok)
      const commit = lookup.ok ? lookup.info.commit : null
      const installed = submodule?.status?.head ?? lockState.lock?.commit
      if (!force && commit && installed === commit) {
        setUpToDate(commit)
        return
      }
      setReport(
        await prepareUpdate({
          theme,
          source,
          lock: lockState.lock,
          siteParams,
          siteTemplateKeys,
          ignore,
          commitBefore: commit,
          mode: submodule ? 'submodule' : 'folder',
          // A clean submodule checkout is exactly the committed version: a reliable merge base.
          trusted: submodule !== null && submodule.status?.initialized === true && submodule.status.changes.length === 0,
        }),
      )
    } catch (e) {
      setError(e)
    } finally {
      setBusy(null)
    }
  }

  const edits = localEdits ? localEdits.added.length + localEdits.changed.length + localEdits.removed.length : 0
  const currentCommit = submodule?.status?.head ?? lockState.lock?.commit

  return (
    <div className="space-y-6">
      <p className="text-sm text-zinc-600 dark:text-zinc-400">{t('theme.update.intro')}</p>
      {mode.kind === 'other' && <Notice>{t('theme.update.notInThemes', { root: theme.label })}</Notice>}
      {submodule && (
        <p className="text-sm">
          {t('theme.update.submodule', { path: submodule.submodule.path, version: submodule.status?.describe ?? shortSha(submodule.status?.head) ?? '?' })}
        </p>
      )}
      {submodule && submodule.status && !submodule.status.initialized && <Notice>{t('theme.update.submoduleNotInit', { path: submodule.submodule.path })}</Notice>}
      {submodule && (submodule.status?.changes.length ?? 0) > 0 && (
        <Notice>{t('theme.update.submoduleChanges', { path: submodule.submodule.path, files: submodule.status!.changes.slice(0, 10).join(', ') })}</Notice>
      )}
      {done && (
        <p role="status" className="text-sm text-emerald-700 dark:text-emerald-400">
          ✓ {done.submodule ? t('theme.update.submoduleApplied', { path: done.submodule.path, version: done.submodule.describe ?? shortSha(done.submodule.head) }) : t('theme.update.applied')}
        </p>
      )}

      <section aria-labelledby="update-source" className="space-y-2">
        <h3 id="update-source" className="text-sm font-semibold uppercase tracking-wide text-zinc-600 dark:text-zinc-400">
          {t('theme.update.source')}
        </h3>
        {lockState.lock ? (
          <p className="text-sm">
            {t('theme.update.locked', {
              repo: `${lockState.lock.source.owner}/${lockState.lock.source.repo}`,
              reference: lockState.lock.source.reference ?? t('theme.update.defaultBranch'),
              date: lockState.lock.installedAt.slice(0, 10),
            })}
          </p>
        ) : (
          !submodule && <p className="text-sm text-zinc-600 dark:text-zinc-400">{t('theme.update.noLock')}</p>
        )}
        <div className="flex flex-wrap items-end gap-3">
          <label className="field min-w-72 flex-1">
            <span>{t('theme.update.repo')}</span>
            <input value={repo} placeholder="https://github.com/owner/repo" onChange={(e) => setRepo(e.target.value)} />
          </label>
          <label className="field w-48">
            <span>{t('theme.update.reference')}</span>
            <input
              value={reference}
              list="theme-update-tags"
              placeholder={repoTags.defaultBranch ?? t('theme.update.defaultBranch')}
              onChange={(e) => setReference(e.target.value)}
            />
            <datalist id="theme-update-tags">
              {repoTags.tags.map((tag) => (
                <option key={tag} value={tag} />
              ))}
            </datalist>
          </label>
          {!lockState.lock && !submodule && (
            <button className="btn" disabled={!source || busy !== null} onClick={() => void createLock()}>
              {busy === 'lock' ? t('theme.update.hashing') : t('theme.update.createLock')}
            </button>
          )}
        </div>
        {repo && !parsed && <p className="text-xs text-red-700 dark:text-red-400">{t('theme.update.badRepo')}</p>}
        {(repoTags.failed || offline) && <p className="text-xs text-zinc-500">{t('theme.update.offline')}</p>}
        {currentCommit && <p className="text-xs text-zinc-500">{t('theme.update.installedCommit', { sha: shortSha(currentCommit) })}</p>}
      </section>

      {lockState.lock && !submodule && (
        <section aria-labelledby="update-local" className="space-y-1">
          <h3 id="update-local" className="text-sm font-semibold uppercase tracking-wide text-zinc-600 dark:text-zinc-400">
            {t('theme.update.localEdits')}
          </h3>
          {localEdits === null ? (
            <p className="text-sm text-zinc-500">{t('theme.update.hashing')}</p>
          ) : edits === 0 ? (
            <p className="text-sm text-emerald-700 dark:text-emerald-400">✓ {t('theme.update.noLocalEdits')}</p>
          ) : (
            <div className="rounded-md border border-amber-300 bg-amber-50 p-2 text-sm text-amber-900 dark:border-amber-800 dark:bg-amber-950 dark:text-amber-100">
              <p>{t('theme.update.localEditsWarning', { count: edits })}</p>
              <FileList diff={localEdits} />
            </div>
          )}
        </section>
      )}

      {!report && (
        <div className="flex flex-wrap items-center gap-3">
          <button className="btn btn-primary" disabled={!source || !updatable || busy !== null} onClick={() => void check(false)}>
            {busy === 'stage' ? t('theme.update.downloading') : t('theme.update.check')}
          </button>
          {upToDate && (
            <>
              <span role="status" className="text-sm text-emerald-700 dark:text-emerald-400">
                ✓ {t('theme.update.upToDate', { sha: shortSha(upToDate) })}
              </span>
              <button className="btn" disabled={busy !== null} onClick={() => void check(true)}>
                {t('theme.update.downloadAnyway')}
              </button>
            </>
          )}
        </div>
      )}
      {error !== null && <ErrorNote error={error} />}

      {report && report.source && (
        <UpdateReview
          report={report}
          hugoVersion={hugoVersion}
          title={t('theme.update.reviewTitle', { name: report.newTheme.name, reference: report.source.reference ?? t('theme.update.defaultBranch') })}
          header={
            <p className="text-sm text-zinc-600 dark:text-zinc-400">
              {t('theme.update.commits', {
                current: shortSha(currentCommit) || t('theme.update.unknownCommit'),
                next: shortSha(report.commit) || t('theme.update.unknownCommit'),
              })}
              {report.commitApproximate && <span className="ml-1 text-amber-700 dark:text-amber-400">{t('theme.update.approximate')}</span>}
              {report.commit !== null && report.commit === currentCommit && <span className="ml-1">· {t('theme.update.sameCommit')}</span>}
            </p>
          }
          applyTheme={async () => {
            if (report.mode === 'submodule' && submodule) {
              // The exact commit that was reviewed when GitHub told us; otherwise the reference.
              const ref = report.commit ?? report.source?.reference ?? 'origin/HEAD'
              const status = await moduleApi.submoduleCheckout(submodule.submodule.path, ref)
              await api.themeDiscardUpdate(report.newTheme.name).catch(() => undefined)
              return status
            }
            await api.themeApplyUpdate(report.newTheme.name)
            return null
          }}
          finish={async () => {
            const lock = makeLock(report.newTheme.name, report.source!, report.newHashes, new Date(), report.commit)
            await api.writeText(LOCK_PATH, lockText(lock), lockState.version ?? '')
          }}
          onCancel={async () => {
            setReport(null)
            await api.themeDiscardUpdate(theme.name).catch(() => undefined)
          }}
          onApplied={(status) => {
            setReport(null)
            setDone({ submodule: status })
            setReloadKey((k) => k + 1)
            if (status) onModeChanged()
            onUpdated()
          }}
        />
      )}

      {lockChange && (
        <ChangesDialog
          title={t('theme.update.lockTitle')}
          texts={[lockChange]}
          skipValidation
          onClose={() => setLockChange(null)}
          onWritten={() => {
            setLockChange(null)
            setReloadKey((k) => k + 1)
          }}
        />
      )}
    </div>
  )
}

interface AppliedModuleChange {
  before: GoModTexts
  from: string
  to: string
  vendored: boolean
  /** Vendored, but `hugo mod vendor` was not run yet. */
  vendorPending: boolean
}

/** The last applied module update per module path, so Undo survives the theme screen reloading. */
const appliedModuleChanges = new Map<string, AppliedModuleChange>()

function sameTexts(a: GoModTexts, b: GoModTexts): boolean {
  return a.goMod === b.goMod && a.goSum === b.goSum
}

/** Themes that are Hugo Modules: `hugo mod get <module>@<version>`, reviewed, undoable. */
function ModuleUpdate({ theme, siteParams, siteTemplateKeys, hugoVersion, ignore, onUpdated, module }: Props & { module: HugoModule }) {
  const { t } = useTranslation()
  // `hugo mod get` wants the module path; a replaced module only knows it from its go.mod.
  const modulePath = /^[.\\/]|^[a-zA-Z]:/.test(module.path) ? (module.modulePath ?? module.path) : module.path
  const github = githubModule(modulePath)
  const repoTags = useRepoTags(github)
  const tags = moduleTags(repoTags.tags, github?.major ?? null)
  const [version, setVersion] = useState('')
  const [busy, setBusy] = useState<'get' | 'undo' | 'vendor' | null>(null)
  const [error, setError] = useState<unknown>(null)
  const [report, setReport] = useState<UpdateReport | null>(null)
  const [same, setSame] = useState(false)
  const [vendor, setVendor] = useState(module.vendored)
  const [applied, setAppliedState] = useState<AppliedModuleChange | null>(() => appliedModuleChanges.get(modulePath) ?? null)
  const setApplied = (change: AppliedModuleChange | null) => {
    if (change) appliedModuleChanges.set(modulePath, change)
    else appliedModuleChanges.delete(modulePath)
    setAppliedState(change)
  }
  const [message, setMessage] = useState<string | null>(null)
  const chosen = version.trim() || tags[0] || 'latest'

  async function fetchVersion() {
    setBusy('get')
    setError(null)
    setSame(false)
    setMessage(null)
    try {
      const result = await moduleApi.modGet(modulePath, chosen)
      if (sameTexts(result.before, result.after)) {
        setSame(true)
        return
      }
      try {
        // A vendored site keeps reading _vendor/: ask for the module cache's view.
        const modules = await moduleApi.moduleList(module.vendored)
        const next = modules.find((m) => m.path === modulePath || m.modulePath === modulePath)
        if (!next) throw new Error(t('theme.update.moduleNotFound', { path: modulePath }))
        setReport(
          await prepareModuleUpdate({
            theme,
            newComponent: moduleComponent(next),
            change: { path: modulePath, from: module.version, to: next.version, vendored: module.vendored, goMod: result },
            siteParams,
            siteTemplateKeys,
            ignore,
          }),
        )
      } catch (e) {
        await moduleApi.modRestore(result.before).catch(() => undefined)
        throw e
      }
    } catch (e) {
      setError(e)
    } finally {
      setBusy(null)
    }
  }

  async function undo() {
    if (!applied) return
    setBusy('undo')
    setError(null)
    try {
      await moduleApi.modRestore(applied.before)
      if (applied.vendored) await moduleApi.modVendor()
      setMessage(t('theme.update.undone', { version: applied.from }))
      setApplied(null)
      onUpdated()
    } catch (e) {
      setError(e)
    } finally {
      setBusy(null)
    }
  }

  async function runVendor() {
    setBusy('vendor')
    setError(null)
    try {
      await moduleApi.modVendor()
      if (applied) setApplied({ ...applied, vendorPending: false })
      setMessage(t('theme.update.vendorDone'))
      onUpdated()
    } catch (e) {
      setError(e)
    } finally {
      setBusy(null)
    }
  }

  return (
    <div className="space-y-6">
      <p className="text-sm text-zinc-600 dark:text-zinc-400">{t('theme.update.intro')}</p>
      <section aria-labelledby="update-source" className="space-y-2">
        <h3 id="update-source" className="text-sm font-semibold uppercase tracking-wide text-zinc-600 dark:text-zinc-400">
          {t('theme.update.source')}
        </h3>
        <p className="text-sm">{t('theme.update.module', { path: modulePath, version: module.version })}</p>
        {module.vendored && <p className="text-xs text-zinc-500">{t('theme.update.moduleVendored', { dir: module.siteDir ?? '_vendor/' })}</p>}
        {!report && (
          <div className="flex flex-wrap items-end gap-3">
            <label className="field w-64">
              <span>{t('theme.update.moduleVersion')}</span>
              <input value={version} list="theme-module-tags" placeholder={tags[0] ?? 'latest'} onChange={(e) => setVersion(e.target.value)} />
              <datalist id="theme-module-tags">
                {['latest', ...tags].map((tag) => (
                  <option key={tag} value={tag} />
                ))}
              </datalist>
            </label>
            <button className="btn btn-primary" disabled={busy !== null} onClick={() => void fetchVersion()}>
              {busy === 'get' ? t('theme.update.moduleFetching') : t('theme.update.moduleFetch', { version: chosen })}
            </button>
          </div>
        )}
        <p className="text-xs text-zinc-500">{github ? (repoTags.failed ? t('theme.update.offline') : t('theme.update.moduleVersionHint')) : t('theme.update.moduleNoGithub')}</p>
        {same && (
          <p role="status" className="text-sm text-emerald-700 dark:text-emerald-400">
            ✓ {t('theme.update.moduleSame', { version: chosen })}
          </p>
        )}
      </section>

      {applied && (
        <div role="status" className="space-y-2 rounded-md border border-emerald-300 bg-emerald-50 p-3 text-sm text-emerald-900 dark:border-emerald-800 dark:bg-emerald-950 dark:text-emerald-100">
          <p>✓ {t('theme.update.moduleApplied', { version: applied.to })}</p>
          {applied.vendorPending && (
            <p>
              {t('theme.update.vendorNeeded')}{' '}
              <button className="btn" disabled={busy !== null} onClick={() => void runVendor()}>
                {t('theme.update.vendorRunNow')}
              </button>
            </p>
          )}
          <p className="text-xs">{t('theme.update.undoNote')}</p>
          <button className="btn" disabled={busy !== null} onClick={() => void undo()}>
            {t('theme.update.undo')}
          </button>
        </div>
      )}
      {message && (
        <p role="status" className="text-sm text-emerald-700 dark:text-emerald-400">
          ✓ {message}
        </p>
      )}
      {error !== null && <ErrorNote error={error} />}

      {report?.module && (
        <UpdateReview
          report={report}
          hugoVersion={hugoVersion}
          title={t('theme.update.moduleReview', { name: theme.name, from: report.module.from || '?', to: report.module.to || chosen })}
          header={
            <div className="space-y-2">
              <p className="text-sm text-zinc-600 dark:text-zinc-400">{t('theme.update.goModChanges')}</p>
              {report.module.goMod.before.goMod !== report.module.goMod.after.goMod && (
                <div>
                  <p className="font-mono text-xs">go.mod</p>
                  <DiffView before={report.module.goMod.before.goMod ?? ''} after={report.module.goMod.after.goMod ?? ''} />
                </div>
              )}
              {report.module.goMod.before.goSum !== report.module.goMod.after.goSum && (
                <div>
                  <p className="font-mono text-xs">go.sum</p>
                  <DiffView before={report.module.goMod.before.goSum ?? ''} after={report.module.goMod.after.goSum ?? ''} />
                </div>
              )}
              {report.module.vendored && (
                <label className="flex items-center gap-2 text-sm">
                  <input type="checkbox" className="accent-sky-700" checked={vendor} onChange={(e) => setVendor(e.target.checked)} />
                  {t('theme.update.vendorRun')}
                </label>
              )}
              {report.module.vendored && !vendor && <p className="text-xs text-amber-700 dark:text-amber-400">{t('theme.update.vendorNeeded')}</p>}
            </div>
          }
          applyTheme={async () => null}
          finish={async () => {
            if (report.module!.vendored && vendor) await moduleApi.modVendor()
          }}
          onCancel={async () => {
            const before = report.module!.goMod.before
            setReport(null)
            await moduleApi.modRestore(before).catch((e) => setError(e))
          }}
          onApplied={() => {
            const change = report.module!
            setApplied({ before: change.goMod.before, from: change.from, to: change.to, vendored: change.vendored, vendorPending: change.vendored && !vendor })
            setReport(null)
            setVersion('')
            onUpdated()
          }}
        />
      )}
    </div>
  )
}

function FileList({ diff, limit = 30 }: { diff: TreeDiff; limit?: number }) {
  const { t } = useTranslation()
  const rows = [
    ...diff.changed.map((p) => ['changed', p] as const),
    ...diff.added.map((p) => ['added', p] as const),
    ...diff.removed.map((p) => ['removed', p] as const),
  ]
  return (
    <ul className="mt-1 max-h-48 overflow-auto font-mono text-xs">
      {rows.slice(0, limit).map(([kind, path]) => (
        <li key={kind + path}>
          <span className="inline-block w-20 font-sans">{t(`theme.update.file.${kind}`)}</span>
          {path}
        </li>
      ))}
      {rows.length > limit && <li className="font-sans">{t('theme.update.more', { count: rows.length - limit })}</li>}
    </ul>
  )
}

function UpdateReview(props: {
  report: UpdateReport
  hugoVersion: HugoVersion | null
  title: string
  header: ReactNode
  /** Puts the new version in place (folder swap, submodule checkout); nothing for modules. */
  applyTheme(): Promise<SubmoduleStatus | null>
  /** After the overrides: the lock file, `hugo mod vendor`… */
  finish(): Promise<void>
  onCancel(): Promise<void>
  onApplied(submodule: SubmoduleStatus | null): void
}) {
  const { t } = useTranslation()
  const { report } = props
  const changing = report.overrides.filter((o) => o.drift.kind !== 'unchanged')
  const [actions, setActions] = useState<Record<string, OverrideAction>>(() => Object.fromEntries(changing.map((o) => [o.entry.sitePath, defaultAction(o.drift.kind)])))
  const [edited, setEdited] = useState<Record<string, string>>(() =>
    Object.fromEntries(changing.filter((o) => o.drift.merged !== undefined).map((o) => [o.entry.sitePath, o.drift.merged!])),
  )
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState<unknown>(null)
  const versionOk = versionAtLeast(props.hugoVersion, report.newTheme.minVersion ?? undefined)
  const unresolved = changing.filter((o) => actions[o.entry.sitePath] === 'edit' && hasConflictMarkers(edited[o.entry.sitePath] ?? ''))
  const fileCount = report.files.added.length + report.files.changed.length + report.files.removed.length

  async function apply() {
    setBusy(true)
    setError(null)
    try {
      const submodule = await props.applyTheme()
      for (const item of changing) {
        const action = actions[item.entry.sitePath]
        const path = item.entry.sitePath
        if (action === 'delete') await api.siteDeleteOverride(path)
        else if (action === 'merge' && item.drift.merged !== undefined) await api.writeText(path, item.drift.merged, item.siteVersion)
        else if (action === 'edit') await api.writeText(path, edited[path] ?? item.siteText, item.siteVersion)
        else if (action === 'theirs' && item.newText !== null) await api.writeText(path, item.newText, item.siteVersion)
      }
      await props.finish()
      props.onApplied(submodule)
    } catch (e) {
      setError(e)
    } finally {
      setBusy(false)
    }
  }

  return (
    <section aria-labelledby="update-review" className="space-y-5 rounded-lg border border-zinc-200 p-4 dark:border-zinc-800">
      <h3 id="update-review" className="text-base font-semibold">
        {props.title}
      </h3>
      {props.header}
      {report.newTheme.minVersion && (
        <p className={`text-sm ${versionOk === false ? 'font-medium text-red-700 dark:text-red-400' : 'text-zinc-600 dark:text-zinc-400'}`}>
          {versionOk === false ? t('theme.update.versionTooOld', { want: report.newTheme.minVersion }) : t('theme.update.versionOk', { want: report.newTheme.minVersion })}
        </p>
      )}

      <div>
        <h4 className="text-sm font-medium">{t('theme.update.filesTitle', { count: fileCount })}</h4>
        {fileCount === 0 ? <p className="text-sm text-zinc-500">{t('theme.update.sameFiles')}</p> : <FileList diff={report.files} />}
        {report.localEdits && report.localEdits.changed.length + report.localEdits.added.length > 0 && (
          <p className="mt-1 text-xs text-amber-700 dark:text-amber-400">{t('theme.update.localEditsLost')}</p>
        )}
        {!report.localEdits && report.mode === 'folder' && <p className="mt-1 text-xs text-zinc-500">{t('theme.update.noLockBase')}</p>}
      </div>

      <div className="space-y-2">
        <h4 className="text-sm font-medium">{t('theme.update.overridesTitle', { count: changing.length })}</h4>
        {changing.length === 0 && <p className="text-sm text-zinc-500">{t('theme.update.noDrift')}</p>}
        {changing.map((item) => (
          <DriftRow
            key={item.entry.sitePath}
            item={item}
            action={actions[item.entry.sitePath]}
            onAction={(a) => setActions({ ...actions, [item.entry.sitePath]: a })}
            text={edited[item.entry.sitePath] ?? item.drift.merged ?? item.siteText}
            onText={(text) => setEdited({ ...edited, [item.entry.sitePath]: text })}
          />
        ))}
      </div>

      {report.i18n.length > 0 && <I18nReview drifts={report.i18n} />}

      <div className="grid gap-4 sm:grid-cols-2">
        <div>
          <h4 className="text-sm font-medium">{t('theme.update.paramsAdded', { count: report.params.added.length })}</h4>
          <p className="font-mono text-xs text-zinc-600 dark:text-zinc-400">{report.params.added.join(', ') || '—'}</p>
        </div>
        <div>
          <h4 className="text-sm font-medium">{t('theme.update.paramsRemoved', { count: report.params.removed.length })}</h4>
          <p className="font-mono text-xs text-zinc-600 dark:text-zinc-400">{report.params.removed.join(', ') || '—'}</p>
        </div>
      </div>
      {report.unusedAfter.length > 0 && (
        <p className="text-sm text-amber-700 dark:text-amber-400">{t('theme.update.unusedAfter', { keys: report.unusedAfter.join(', ') })}</p>
      )}
      {report.lostHooks.length > 0 && (
        <div className="text-sm text-amber-700 dark:text-amber-400">
          <p>{t('theme.update.lostHooks')}</p>
          <ul className="font-mono text-xs">
            {report.lostHooks.map((h) => (
              <li key={h.sitePath}>
                {h.sitePath} → {h.hook}
              </li>
            ))}
          </ul>
        </div>
      )}

      {unresolved.length > 0 && <p className="text-sm text-red-700 dark:text-red-400">{t('theme.update.unresolved', { count: unresolved.length })}</p>}
      {error !== null && <ErrorNote error={error} />}
      <div className="flex justify-end gap-2">
        <button className="btn" disabled={busy} onClick={() => void props.onCancel()}>
          {t('common.cancel')}
        </button>
        <button className="btn btn-primary" disabled={busy || unresolved.length > 0} onClick={() => void apply()}>
          {busy ? t('common.saving') : t('theme.update.apply')}
        </button>
      </div>
    </section>
  )
}

function i18nText(value: I18nValue | null): string {
  if (value === null) return '—'
  if (typeof value === 'string') return value
  return Object.entries(value)
    .map(([form, text]) => `${form}: ${text}`)
    .join(' · ')
}

/** Site i18n keys whose theme text changed or went away (Hugo merges them key by key). */
function I18nReview({ drifts }: { drifts: I18nDrift[] }) {
  const { t } = useTranslation()
  return (
    <div className="space-y-2" data-testid="i18n-drift">
      <h4 className="text-sm font-medium">{t('theme.update.i18nTitle', { count: drifts.length })}</h4>
      {drifts.map((drift) => (
        <div key={drift.sitePath} className="space-y-1 rounded-md border border-zinc-200 p-3 text-sm dark:border-zinc-800" data-i18n={drift.sitePath}>
          <code>{drift.sitePath}</code>
          {drift.changed.length > 0 && (
            <>
              <p className="text-xs text-zinc-600 dark:text-zinc-400">{t('theme.update.i18nChanged')}</p>
              <ul className="space-y-1 text-xs">
                {drift.changed.map((k) => (
                  <li key={k.key}>
                    <code className="font-semibold">{k.key}</code> — {t('theme.update.i18nTheme', { before: i18nText(k.before), after: i18nText(k.after) })};{' '}
                    {t('theme.update.i18nYours', { text: i18nText(k.site) })}
                  </li>
                ))}
              </ul>
            </>
          )}
          {drift.removed.length > 0 && (
            <>
              <p className="text-xs text-amber-700 dark:text-amber-400">{t('theme.update.i18nRemoved')}</p>
              <p className="font-mono text-xs">{drift.removed.map((k) => k.key).join(', ')}</p>
            </>
          )}
        </div>
      ))}
    </div>
  )
}

function DriftRow(props: { item: OverrideItem; action: OverrideAction; onAction(a: OverrideAction): void; text: string; onText(text: string): void }) {
  const { t } = useTranslation()
  const { item } = props
  const kind = item.drift.kind
  const choices: OverrideAction[] =
    kind === 'nowIdentical' ? ['delete', 'keep'] : kind === 'merged' ? ['merge', 'keep', 'theirs'] : kind === 'conflict' ? ['keep', 'edit', 'theirs'] : kind === 'noBase' ? ['keep', 'theirs'] : ['keep']
  const name = `drift-${item.entry.sitePath}`
  return (
    <div className="space-y-2 rounded-md border border-zinc-200 p-3 dark:border-zinc-800" data-override={item.entry.sitePath}>
      <p className="flex flex-wrap items-center gap-2 text-sm">
        <code>{item.entry.sitePath}</code>
        <span className="text-xs text-zinc-600 dark:text-zinc-400">{t(`theme.update.drift.${kind}`, { count: item.drift.conflicts ?? 0 })}</span>
      </p>
      {item.baseUnverified && kind !== 'themeRemoved' && <p className="text-xs text-zinc-500">{t('theme.update.baseUnverified')}</p>}
      <fieldset className="flex flex-wrap gap-4 text-sm" aria-label={t('theme.update.choice', { file: item.entry.sitePath })}>
        {choices.map((choice) => (
          <label key={choice} className="inline-flex items-center gap-1.5">
            <input type="radio" name={name} className="accent-sky-700" checked={props.action === choice} onChange={() => props.onAction(choice)} />
            {t(`theme.update.action.${choice}`)}
          </label>
        ))}
      </fieldset>
      {item.baseText !== null && item.newText !== null && (
        <details>
          <summary className="cursor-pointer text-xs text-sky-700 dark:text-sky-400">{t('theme.update.threeWay')}</summary>
          <div className="mt-2 space-y-2">
            <p className="text-xs text-zinc-500">{t('theme.update.themeChanged')}</p>
            <DiffView before={item.baseText} after={item.newText} />
            <p className="text-xs text-zinc-500">{t('theme.update.youChanged')}</p>
            <DiffView before={item.baseText} after={item.siteText} />
          </div>
        </details>
      )}
      {item.baseText === null && item.newText !== null && (
        <details>
          <summary className="cursor-pointer text-xs text-sky-700 dark:text-sky-400">{t('theme.update.twoWay')}</summary>
          <DiffView before={item.newText} after={item.siteText} />
        </details>
      )}
      {props.action === 'merge' && item.drift.merged !== undefined && (
        <>
          <p className="text-xs text-zinc-500">{t('theme.update.mergedResult')}</p>
          <DiffView before={item.siteText} after={item.drift.merged} />
        </>
      )}
      {props.action === 'edit' && (
        <textarea
          className="h-64 w-full rounded-md border border-zinc-300 bg-white p-2 font-mono text-xs dark:border-zinc-700 dark:bg-zinc-900"
          aria-label={t('theme.update.editMerged', { file: item.entry.sitePath })}
          value={props.text}
          onChange={(e) => props.onText(e.target.value)}
        />
      )}
    </div>
  )
}
