// Chroma styles shipped with Hugo 0.167 (`markup.highlight.style`), with their light/dark mode.

export interface ChromaStyle {
  name: string
  mode: 'light' | 'dark'
}

const LIGHT = 'light'
const DARK = 'dark'

export const CHROMA_STYLES: readonly ChromaStyle[] = (
  [
    ['abap', LIGHT],
    ['algol', LIGHT],
    ['algol_nu', LIGHT],
    ['arduino', LIGHT],
    ['ashen', DARK],
    ['aura-theme-dark', DARK],
    ['aura-theme-dark-soft', DARK],
    ['autumn', LIGHT],
    ['average', DARK],
    ['base16-snazzy', DARK],
    ['borland', LIGHT],
    ['bw', LIGHT],
    ['catppuccin-frappe', DARK],
    ['catppuccin-latte', LIGHT],
    ['catppuccin-macchiato', DARK],
    ['catppuccin-mocha', DARK],
    ['colorful', LIGHT],
    ['darcula', DARK],
    ['doom-one', DARK],
    ['doom-one2', DARK],
    ['dracula', DARK],
    ['emacs', LIGHT],
    ['evergarden', DARK],
    ['friendly', LIGHT],
    ['fruity', DARK],
    ['github', LIGHT],
    ['github-dark', DARK],
    ['gruvbox', DARK],
    ['gruvbox-light', LIGHT],
    ['hr_high_contrast', LIGHT],
    ['hrdark', LIGHT],
    ['igor', LIGHT],
    ['kanagawa-dragon', DARK],
    ['kanagawa-lotus', LIGHT],
    ['kanagawa-wave', DARK],
    ['lovelace', LIGHT],
    ['manni', LIGHT],
    ['modus-operandi', LIGHT],
    ['modus-vivendi', DARK],
    ['monokai', DARK],
    ['monokailight', LIGHT],
    ['murphy', LIGHT],
    ['native', DARK],
    ['nord', DARK],
    ['nordic', DARK],
    ['onedark', DARK],
    ['onesenterprise', LIGHT],
    ['paraiso-dark', DARK],
    ['paraiso-light', LIGHT],
    ['pastie', LIGHT],
    ['perldoc', LIGHT],
    ['pygments', LIGHT],
    ['rainbow_dash', LIGHT],
    ['rose-pine', DARK],
    ['rose-pine-dawn', LIGHT],
    ['rose-pine-moon', DARK],
    ['rpgle', LIGHT],
    ['rrt', DARK],
    ['solarized-dark', DARK],
    ['solarized-dark256', DARK],
    ['solarized-light', LIGHT],
    ['swapoff', DARK],
    ['tango', LIGHT],
    ['tokyonight-day', LIGHT],
    ['tokyonight-moon', DARK],
    ['tokyonight-night', DARK],
    ['tokyonight-storm', DARK],
    ['trac', LIGHT],
    ['vim', DARK],
    ['vs', LIGHT],
    ['vulcan', DARK],
    ['witchhazel', DARK],
    ['xcode', LIGHT],
    ['xcode-dark', DARK],
  ] as const
).map(([name, mode]) => ({ name, mode }))

export const CHROMA_STYLE_NAMES: readonly string[] = CHROMA_STYLES.map((s) => s.name)
