import type { Strings } from '../../../i18n/types'
import type { keyMessagesEn } from './labels.en'

// Türkçe etiket ve açıklamalar; anahtarları labels.en.ts ile birebir aynı olmak zorunda.
export const keyMessagesTr: Strings<typeof keyMessagesEn> = {
  // Site kimliği
  title: { label: 'Site başlığı', help: 'Sitenin adı. Çoğu tema bunu üst bölümde ve tarayıcı sekmesinde gösterir.' },
  baseURL: {
    label: 'Site adresi (baseURL)',
    help: 'Sitenin herkese açık adresi; protokol dahil ve sonunda eğik çizgiyle, ör. https://ornek.com/. Önizleme sunucusu bunu localhost ile değiştirir.',
  },
  locale: {
    label: 'Yerel ayar',
    help: 'tr ya da en-US gibi dil etiketi. Çeviri dosyalarını seçer, tarih ve sayıları biçimlendirir. languageCode’un yerini aldı (Hugo 0.158).',
  },
  copyright: { label: 'Telif hakkı notu', help: 'Temaların alt bilgide gösterdiği metin, ör. © 2026 Adın Soyadın.' },
  theme: { label: 'Tema', help: 'themes/ altındaki tema klasörü ya da modül yolu. Birden fazla tema varsa ilk sıradaki önceliklidir.' },
  timeZone: {
    label: 'Saat dilimi',
    help: 'Saat farkı yazılmamış tarihler için IANA dilimi (ör. Europe/Istanbul). Boşsa UTC kullanılır.',
  },

  // URL ve kalıcı bağlantılar
  permalinks: {
    label: 'Bölüm başına kalıcı bağlantılar',
    help: 'Her bölüm için adres kalıbı, ör. posts → /:year/:month/:slug/. Bu kısa biçim sayfalara ve terimlere uygulanır.',
  },
  'permalinks/page': { label: 'Sayfa bağlantıları', help: 'Tekil sayfaların adres kalıpları, bölüm başına.' },
  'permalinks/section': { label: 'Bölüm listesi bağlantıları', help: 'Bölüm liste sayfalarının adres kalıpları, bölüm başına.' },
  'permalinks/taxonomy': { label: 'Sınıflandırma listesi bağlantıları', help: 'Tüm terimleri listeleyen sayfaların adres kalıpları, ör. /tags/.' },
  'permalinks/term': { label: 'Terim bağlantıları', help: 'Tek bir terimin sayfasının adres kalıpları, ör. /tags/hugo/.' },
  removePathAccents: {
    label: 'Adreslerdeki aksanları kaldır',
    help: 'Dosya ve bölüm adlarından üretilen adreslerde ü, ş, ç gibi harfleri u, s, c yapar (Gündem → gundem).',
  },
  uglyURLs: { label: 'Uzantılı adresler', help: '/posts/merhaba/ yerine /posts/merhaba.html yayımlar.' },
  disablePathToLower: { label: 'Adreslerde büyük harfleri koru', help: 'Hugo varsayılan olarak bütün adresleri küçük harfe çevirir.' },
  disableAliases: { label: 'Takma adlar için yönlendirme sayfası yok', help: 'Front matter’daki aliases için normalde yazılan HTML yönlendirme dosyalarını oluşturmaz.' },
  relativeURLs: {
    label: 'Göreli adresler',
    help: 'Kökten başlayan bağlantıları sayfaya göreli hâle getirir. Yalnızca diskten doğrudan açılan siteler için; birçok temayı bozar.',
  },
  canonifyURLs: {
    label: 'Mutlak adresler (eski)',
    help: 'Kökten başlayan bağlantıları mutlak yapan eski bir son işlemci. Hugo bunu kaldırabilir; şablonlarda absURL tercih edin.',
  },
  refLinksErrorLevel: { label: 'Kırık ref/relref bağlantıları', help: 'ERROR, hiçbir yere gitmeyen ref ya da relref bağlantısında derlemeyi durdurur; WARNING yalnızca bildirir.' },
  refLinksNotFoundURL: { label: 'Kırık ref bağlantısı adresi', help: 'Çözülemeyen ref ya da relref bağlantısının yerine yazılır.' },

  // İçerik
  summaryLength: { label: 'Özet uzunluğu', help: 'Otomatik özetteki en az kelime sayısı.' },
  mainSections: {
    label: 'Ana bölümler',
    help: 'Temaların ana sayfada listelediği bölümler. Boşsa en çok sayfası olan bölüm kullanılır.',
  },
  buildDrafts: { label: 'Taslakları yayımla', help: 'draft: true olan sayfaları da derler. Genelde yalnızca önizlemede istenir (config/development).' },
  buildFuture: { label: 'İleri tarihli yazıları yayımla', help: 'Yayın tarihi gelecekte olan sayfaları da derler.' },
  buildExpired: { label: 'Süresi dolmuş sayfaları yayımla', help: 'Bitiş tarihi geçmiş sayfaları da derler.' },
  enableEmoji: { label: 'Emoji kısa kodları', help: 'İçerikteki :smile: gibi kodları emojiye çevirir.' },
  disableKinds: {
    label: 'Derlenmeyecek sayfa türleri',
    help: 'Ör. taxonomy, /tags/ liste sayfasını üretmez ama terim sayfaları kalır; sitemap, sitemap.xml’i üretmez.',
  },
  enableGitInfo: { label: 'Git geçmişini kullan', help: 'Her sayfanın son commit’ini okur; böylece lastmod Git’ten gelebilir. git gerekir.' },
  hasCJKLanguage: { label: 'Çince/Japonca/Korece metin', help: 'Özet ve okuma süresi için CJK metinde kelimeleri doğru sayar.' },
  pluralizeListTitles: { label: 'Liste başlıklarını çoğul yap', help: 'Otomatik bölüm başlıklarını çoğul yapar (yalnızca İngilizce kurallarıyla).' },
  capitalizeListTitles: { label: 'Liste başlıklarını büyük harfle başlat', help: 'Otomatik bölüm, sınıflandırma ve terim başlıklarının baş harflerini büyütür.' },
  titleCaseStyle: { label: 'Başlık büyük harf stili', help: 'Otomatik başlıkların nasıl büyütüleceği: ap, chicago, go, firstupper ya da none.' },
  defaultOutputFormat: { label: 'Varsayılan çıktı biçimi', help: 'Başka bir şey ayarlanmadığında kullanılan çıktı biçimi. Normalde html.' },
  newContentEditor: { label: 'Yeni içerik için editör', help: 'hugo new content ile oluşturulan dosyaları açan komut, ör. code.' },
  'frontmatter/date': { label: 'Tarihin kaynakları', help: 'Sayfa tarihi için sırayla denenen front matter alanları (ve :filename, :fileModTime, :git).' },
  'frontmatter/publishDate': { label: 'Yayın tarihinin kaynakları', help: 'Yayın tarihi için sırayla denenen alanlar.' },
  'frontmatter/lastmod': { label: 'Son değişiklik tarihinin kaynakları', help: 'lastmod için sırayla denenen alanlar. :git için Git geçmişi açık olmalı.' },
  'frontmatter/expiryDate': { label: 'Bitiş tarihinin kaynakları', help: 'Bitiş tarihi için sırayla denenen alanlar.' },
  'page/nextPrevSortOrder': { label: 'Sonraki/önceki sırası', help: 'Tüm sitede .Next ve .Prev yönü.' },
  'page/nextPrevInSectionSortOrder': { label: 'Bölüm içinde sonraki/önceki sırası', help: '.NextInSection ve .PrevInSection yönü.' },
  'related/threshold': { label: 'İlgili içerik eşiği', help: '0–100; düşük değerler daha çok (ama daha zayıf) ilgili sayfa bulur.' },
  'related/includeNewer': { label: 'Daha yeni sayfaları da öner', help: 'Varsayılan olarak yalnızca daha eski sayfalar ilgili diye önerilir.' },
  'related/toLower': { label: 'İlgili içerikte büyük/küçük harfi yok say', help: 'Anahtar kelime ve etiketleri karşılaştırmadan önce küçük harfe çevirir.' },
  'related/indices': {
    label: 'İlgili içerik ölçütleri',
    help: 'İlgili sayfaları bulmak için kullanılan front matter alanları ve ağırlıkları. Bu listeyi tanımlamak varsayılanın tamamını değiştirir.',
  },

  // Sınıflandırmalar
  taxonomies: {
    label: 'Sınıflandırmalar',
    help: 'Tekil → çoğul, ör. tag → tags. Listeyi tanımlamak varsayılanları siler; kullanıyorsan tag ve category’yi de bırak.',
  },
  sectionPagesMenu: { label: 'Bölümler için menü', help: 'Üst düzeydeki her bölümü bu menüye otomatik ekler, ör. main.' },

  // Markdown
  'markup/goldmark/renderer/unsafe': {
    label: 'Markdown içinde ham HTML’e izin ver',
    help: 'Kapalıyken Hugo yazılardaki HTML’i bir yorumla değiştirir. Yalnızca içerik yazan herkese güveniyorsan aç.',
  },
  'markup/goldmark/renderer/hardWraps': { label: 'Satır sonlarını olduğu gibi koru', help: 'Paragraf içindeki tek satır sonu da alt satıra geçer (<br>).' },
  'markup/goldmark/extensions/typographer/disable': {
    label: 'Akıllı noktalamayı kapat',
    help: 'Akıllı noktalama "tırnakları", -- ve ... işaretlerini tipografik karakterlere çevirir.',
  },
  'markup/goldmark/extensions/passthrough/enable': {
    label: 'Matematiği olduğu gibi geçir',
    help: 'Aşağıdaki sınırlayıcılar arasındaki LaTeX’i KaTeX ya da MathJax için dokunmadan bırakır.',
  },
  'markup/goldmark/extensions/passthrough/delimiters/block': { label: 'Blok matematik sınırlayıcıları', help: '\\[ … \\] ve $$ … $$ gibi çiftler.' },
  'markup/goldmark/extensions/passthrough/delimiters/inline': { label: 'Satır içi matematik sınırlayıcıları', help: '\\( … \\) gibi çiftler.' },
  'markup/goldmark/parser/attribute/title': { label: 'Başlıklarda öznitelikler', help: 'Başlıktan sonra {#id .sinif} yazmaya izin verir.' },
  'markup/goldmark/parser/attribute/block': { label: 'Bloklarda öznitelikler', help: 'Paragraf, liste, tablo ve diğer bloklarda {.sinif} yazmaya izin verir.' },
  'markup/goldmark/parser/autoHeadingID': { label: 'Başlık kimlikleri', help: 'Bağlantı verilebilsin diye her başlığa bir id verir.' },
  'markup/goldmark/parser/autoIDType': { label: 'Başlık kimliği stili', help: 'github ş gibi harfleri korur; github-ascii atar; blackfriday eski stildir.' },
  'markup/goldmark/parser/autoDefinitionTermID': { label: 'Tanım terimlerine kimlik', help: 'Tanım listesi terimlerine (<dt>) id verir.' },
  'markup/goldmark/parser/wrapStandAloneImageWithinParagraph': {
    label: 'Tek başına görselleri paragrafa sar',
    help: 'Görsel render hook’u <figure> üretiyorsa kapat.',
  },
  'markup/goldmark/renderHooks/image/useEmbedded': {
    label: 'Yerleşik görsel hook’u',
    help: 'Hugo’nun kendi görsel render hook’u ne zaman kullanılsın: auto, never, always ya da temada yoksa fallback.',
  },
  'markup/goldmark/renderHooks/link/useEmbedded': { label: 'Yerleşik bağlantı hook’u', help: 'Hugo’nun kendi bağlantı render hook’u ne zaman kullanılsın.' },
  'markup/goldmark/renderer/xhtml': { label: 'XHTML çıktısı', help: '<br /> gibi kendiliğinden kapanan etiketler yazar.' },
  'markup/goldmark/duplicateResourceFiles': {
    label: 'Paylaşılan kaynakları dil başına kopyala',
    help: 'Çok dilli sitelerde ortak sayfa kaynaklarını her dil için ayrı yayımlar.',
  },
  'markup/goldmark/extensions/table': { label: 'Tablolar', help: '| sütunlu GitHub tarzı tablolar.' },
  'markup/goldmark/extensions/strikethrough': { label: 'Üstü çizili', help: '~~metin~~ üstü çizili olur. Alt simge açıksa kapalı olmalı.' },
  'markup/goldmark/extensions/taskList': { label: 'Görev listeleri', help: '- [ ] ve - [x] onay kutusuna dönüşür.' },
  'markup/goldmark/extensions/definitionList': { label: 'Tanım listeleri', help: 'Terim satırı ve ardından : ile başlayan tanım satırları.' },
  'markup/goldmark/extensions/linkify': { label: 'Çıplak adresleri bağlantı yap', help: 'Metne yazılan adresler bağlantıya dönüşür.' },
  'markup/goldmark/extensions/linkifyProtocol': { label: 'www. bağlantıları için protokol', help: 'www. ile başlayan çıplak bağlantılarda kullanılır.' },
  'markup/goldmark/extensions/footnote/enable': { label: 'Dipnotlar', help: 'Metin[^1] ve aşağıda [^1]: not.' },
  'markup/goldmark/extensions/footnote/backlinkHTML': { label: 'Dipnot dönüş bağlantısı', help: 'Dipnottan metne geri dönen bağlantının HTML’i.' },
  'markup/goldmark/extensions/footnote/enableAutoIDPrefix': {
    label: 'Benzersiz dipnot kimlikleri',
    help: 'Dipnot kimliklerine sayfa başına önek ekler; böylece birden çok yazı aynı liste sayfasında çakışmaz.',
  },
  'markup/goldmark/extensions/typographer/leftDoubleQuote': { label: 'Açılış çift tırnağı', help: 'Açılan " yerine yazılacak karakter, ör. &ldquo; ya da “.' },
  'markup/goldmark/extensions/typographer/rightDoubleQuote': { label: 'Kapanış çift tırnağı', help: 'Kapanan " yerine yazılacak karakter.' },
  'markup/goldmark/extensions/typographer/leftSingleQuote': { label: 'Açılış tek tırnağı', help: 'Açılan \' yerine yazılacak karakter.' },
  'markup/goldmark/extensions/typographer/rightSingleQuote': { label: 'Kapanış tek tırnağı', help: 'Kapanan \' yerine yazılacak karakter.' },
  'markup/goldmark/extensions/typographer/leftAngleQuote': { label: 'Açılış köşeli tırnağı', help: '<< yerine yazılacak karakter, ör. «.' },
  'markup/goldmark/extensions/typographer/rightAngleQuote': { label: 'Kapanış köşeli tırnağı', help: '>> yerine yazılacak karakter, ör. ».' },
  'markup/goldmark/extensions/typographer/apostrophe': { label: 'Kesme işareti', help: 'Kelime içindeki kesme işaretinin yerine yazılacak karakter.' },
  'markup/goldmark/extensions/typographer/enDash': { label: 'Kısa tire (en dash)', help: '-- yerine yazılacak karakter.' },
  'markup/goldmark/extensions/typographer/emDash': { label: 'Uzun tire (em dash)', help: '--- yerine yazılacak karakter.' },
  'markup/goldmark/extensions/typographer/ellipsis': { label: 'Üç nokta', help: '... yerine yazılacak karakter.' },
  'markup/goldmark/extensions/extras/delete/enable': { label: 'Silinmiş metin (~~)', help: '~~metin~~ <del> olur.' },
  'markup/goldmark/extensions/extras/insert/enable': { label: 'Eklenmiş metin (++)', help: '++metin++ <ins> olur.' },
  'markup/goldmark/extensions/extras/mark/enable': { label: 'Vurgulanmış metin (==)', help: '==metin== <mark> olur.' },
  'markup/goldmark/extensions/extras/subscript/enable': { label: 'Alt simge', help: 'H~2~O. Kullanırken üstü çiziliyi kapat.' },
  'markup/goldmark/extensions/extras/superscript/enable': { label: 'Üst simge', help: 'm^2^.' },
  'markup/goldmark/extensions/cjk/enable': { label: 'CJK eklentisi', help: 'Çince, Japonca ve Korece için satır bölme kuralları.' },
  'markup/goldmark/extensions/cjk/eastAsianLineBreaks': { label: 'Doğu Asya satır sonları', help: 'CJK karakterleri arasında satır bölündüğünde boşluk eklenmez.' },
  'markup/goldmark/extensions/cjk/eastAsianLineBreaksStyle': { label: 'Satır sonu stili', help: 'simple ya da css3draft.' },
  'markup/goldmark/extensions/cjk/escapedSpace': { label: 'Kaçışlı boşluklar', help: 'Boşluktan önceki ters eğik çizgi boşluğu kaldırır.' },
  'markup/defaultMarkdownHandler': {
    label: 'Markdown işleyicisi',
    help: 'goldmark yerleşiktir. Diğerleri harici bir program ve security.exec.allow ister.',
  },

  // Kod vurgulama
  'markup/highlight/style': { label: 'Kod renk stili', help: '74 Chroma stilinden biri. Koyu ve açık çiftleri var, ör. github ve github-dark.' },
  'markup/highlight/lineNos': { label: 'Satır numaraları', help: 'Kod bloklarında satır numaraları: satır içinde, tabloda ya da hiç.' },
  'markup/highlight/noClasses': {
    label: 'Renkler HTML içinde',
    help: 'Renkler HTML’e yazılır. CSS sınıfları (hugo gen chromastyles) kullanıp açık/koyu temaya uymak için kapat.',
  },
  'markup/highlight/codeFences': { label: 'Kod çitlerini renklendir', help: '``` bloklarını renklendirir.' },
  'markup/highlight/guessSyntax': { label: 'Dili tahmin et', help: 'Dili belirtilmemiş kod bloklarını tahmin ederek renklendirir.' },
  'markup/highlight/lineNumbersInTable': { label: 'Satır numaraları tabloda', help: 'Numaraları ayrı sütuna koyar; kopyalarken numaralar gelmez.' },
  'markup/highlight/lineNoStart': { label: 'İlk satır numarası', help: 'İlk satırın numarası.' },
  'markup/highlight/anchorLineNos': { label: 'Satır numarası bağlantıları', help: 'Satır numaraları o satıra giden bağlantı olur.' },
  'markup/highlight/lineAnchors': { label: 'Satır bağlantısı öneki', help: 'Satır bağlantısı kimliklerinin öneki; bir sayfada birden çok blok varsa işe yarar.' },
  'markup/highlight/hl_Lines': { label: 'Vurgulanacak satırlar', help: 'Ör. 2-4 7. Genelde blok başına ayarlanır.' },
  'markup/highlight/hl_inline': { label: 'Sarmalayıcı öğe yok', help: 'Çevreleyen kapsayıcı olmadan vurgular.' },
  'markup/highlight/tabWidth': { label: 'Sekme genişliği', help: 'Sekme başına boşluk sayısı; yalnızca renkler HTML içindeyken.' },
  'markup/highlight/wrapperClass': { label: 'Sarmalayıcı sınıfı', help: 'Kod bloklarını çevreleyen öğenin CSS sınıfı.' },

  // İçindekiler
  'markup/tableOfContents/startLevel': { label: 'İlk başlık düzeyi', help: 'İçindekilerdeki en üst başlık düzeyi (2 = ##).' },
  'markup/tableOfContents/endLevel': { label: 'Son başlık düzeyi', help: 'Dahil edilen en derin başlık düzeyi; en az ilk düzey kadar.' },
  'markup/tableOfContents/ordered': { label: 'Numaralı liste', help: 'Madde işaretleri yerine numaralı liste (<ol>) kullanır.' },

  // SEO
  enableRobotsTXT: { label: 'robots.txt oluştur', help: '/robots.txt yazar. Yerleşik olan her şeye izin verir; tema ya da layouts/robots.txt değiştirebilir.' },
  'sitemap/changeFreq': { label: 'Site haritası değişim sıklığı', help: 'Her sayfa için varsayılan changefreq; boşsa yazılmaz.' },
  'sitemap/priority': { label: 'Site haritası önceliği', help: '0.0–1.0; -1 yazılmaz demektir.' },
  'sitemap/filename': { label: 'Site haritası dosya adı', help: 'Site haritası dosyasının adı.' },
  'sitemap/disable': { label: 'Sayfaları site haritasına alma', help: 'Genelde sayfa başına front matter’da ayarlanır. Site haritasını tümden kaldırmak için derlenmeyecek türlere sitemap ekle.' },
  disableHugoGeneratorInject: { label: 'Generator etiketi yok', help: 'Ana sayfadaki <meta name="generator" content="Hugo …"> etiketini yazmaz.' },

  // Çıktılar
  'outputs/home': { label: 'Ana sayfa çıktıları', help: 'Ana sayfa için üretilen dosyalar. İlki asıl çıktıdır; /llms.txt için llms ekle.' },
  'outputs/page': { label: 'Sayfa çıktıları', help: 'Her tekil sayfa için üretilen dosyalar.' },
  'outputs/section': { label: 'Bölüm çıktıları', help: 'Bölüm liste sayfaları için üretilen dosyalar (html, rss…).' },
  'outputs/taxonomy': { label: 'Sınıflandırma listesi çıktıları', help: 'Tüm terimleri listeleyen sayfalar için üretilen dosyalar.' },
  'outputs/term': { label: 'Terim çıktıları', help: 'Her terimin sayfası için üretilen dosyalar.' },
  outputFormats: {
    label: 'Özel çıktı biçimleri',
    help: 'Yeni ya da değiştirilmiş biçimler, ör. llms (text/plain, baseName llms). Yerleşik biçimler her zaman kullanılabilir.',
  },
  mediaTypes: { label: 'Medya türleri', help: 'Ek ya da değiştirilmiş medya türleri ve dosya uzantıları.' },

  // Sayfalama
  'pagination/pagerSize': { label: 'Sayfa başına öge', help: 'Sayfalı bir listenin her sayfasındaki öge sayısı. paginate’in yerini aldı.' },
  'pagination/path': { label: 'Sayfa yolu kelimesi', help: '/page/2/ içindeki kelime; Türkçe sitelerde sık kullanılan sayfa. paginatePath’in yerini aldı.' },
  'pagination/disableAliases': { label: '1. sayfa için yönlendirme yok', help: '/page/1/ adresini listenin kendisine yönlendirmez.' },

  // Görseller
  'imaging/jpeg/quality': { label: 'JPEG kalitesi', help: '1–100. Yüksek değer daha net ve daha büyük dosya demek.' },
  'imaging/webp/quality': { label: 'WebP kalitesi', help: '1–100, kayıplı WebP için.' },
  'imaging/avif/quality': { label: 'AVIF kalitesi', help: '1–100. AVIF 60 aşağı yukarı JPEG 75 gibi görünür.' },
  'imaging/anchor': { label: 'Kırpma odağı', help: 'Fill ve Crop görselin hangi kısmını korusun. Smart ilginç bölgeyi arar.' },
  'imaging/resampleFilter': { label: 'Boyutlandırma filtresi', help: 'box hızlıdır; lanczos ve catmullRom daha keskin ama daha yavaştır.' },
  'imaging/bgColor': { label: 'Arka plan rengi', help: 'Saydamlığı olmayan bir biçime dönüştürürken saydam alanları doldurur.' },
  'imaging/webp/compression': { label: 'WebP sıkıştırması', help: 'lossy (kayıplı) ya da lossless (kayıpsız).' },
  'imaging/webp/hint': { label: 'WebP görsel türü', help: 'Kodlayıcıyı ayarlar: photo, picture, drawing, icon ya da text.' },
  'imaging/webp/method': { label: 'WebP çabası', help: '0–6; yüksek değer daha küçük ama daha yavaş.' },
  'imaging/webp/useSharpYuv': { label: 'Daha keskin WebP renkleri', help: 'Daha doğru renk dönüşümü, daha yavaş.' },
  'imaging/avif/compression': { label: 'AVIF sıkıştırması', help: 'lossy (kayıplı) ya da lossless (kayıpsız).' },
  'imaging/avif/hint': { label: 'AVIF görsel türü', help: 'photo ve picture daha az renk verisi kullanır; diğerleri tam rengi korur.' },
  'imaging/avif/encoderSpeed': { label: 'AVIF hızı', help: '1–10; düşük değer daha küçük ama çok daha yavaş (5’in altı çok yavaş).' },
  'imaging/meta/sources': { label: 'Üst veri kaynakları', help: '.Meta’nın görsel üst verisini okuduğu yerler: exif, iptc, xmp.' },
  'imaging/meta/fields': { label: 'Üst veri alanları', help: 'Okunacak alanların glob kalıpları; varsayılan GPS ve kamera ayrıntılarını dışarıda bırakır.' },

  // Gizlilik
  'privacy/disqus/disable': { label: 'Disqus’u kapat', help: 'Hugo’nun yerleşik Disqus şablonunu devre dışı bırakır.' },
  'privacy/googleAnalytics/disable': { label: 'Google Analytics’i kapat', help: 'Hugo’nun yerleşik Google Analytics şablonunu devre dışı bırakır.' },
  'privacy/googleAnalytics/respectDoNotTrack': { label: '“İzleme” isteğine uy', help: 'İzlenmek istemeyen ziyaretçiler için analiz yapılmaz (Hugo 0.153’ten beri varsayılan).' },
  'privacy/instagram/disable': { label: 'Instagram’ı kapat', help: 'instagram kısa kodunu devre dışı bırakır.' },
  'privacy/instagram/simple': { label: 'Sade Instagram gömmeleri', help: 'Instagram betiği olmadan statik bir kart.' },
  'privacy/vimeo/disable': { label: 'Vimeo’yu kapat', help: 'vimeo kısa kodunu devre dışı bırakır.' },
  'privacy/vimeo/enableDNT': { label: 'İzlemesiz Vimeo', help: 'Vimeo’dan izleyicileri izlememesini ister.' },
  'privacy/vimeo/simple': { label: 'Sade Vimeo gömmeleri', help: 'Oynatıcı yerine küçük resimli bir bağlantı.' },
  'privacy/x/disable': { label: 'X’i (Twitter) kapat', help: 'x kısa kodunu devre dışı bırakır.' },
  'privacy/x/enableDNT': { label: 'İzlemesiz X', help: 'X’ten gömmeyi izleme için kullanmamasını ister.' },
  'privacy/x/simple': { label: 'Sade X gömmeleri', help: 'X betiği olmadan statik gönderi.' },
  'privacy/youTube/disable': { label: 'YouTube’u kapat', help: 'youtube kısa kodunu devre dışı bırakır.' },
  'privacy/youTube/privacyEnhanced': { label: 'YouTube gizlilik modu', help: 'Videoları youtube-nocookie.com üzerinden gömer.' },

  // Servisler
  'services/googleAnalytics/id': { label: 'Google Analytics kimliği', help: 'Yerleşik şablon için G-XXXXXXXXXX etiketi. Çoğu zaman yalnızca production’da ayarlanır.' },
  'services/disqus/shortname': { label: 'Disqus kısa adı', help: 'Yerleşik yorum şablonu için sitenin Disqus’taki adı.' },
  'services/rss/limit': { label: 'RSS öge sınırı', help: 'Akışlardaki en fazla öge sayısı; -1 hepsi demek.' },
  'services/x/disableInlineCSS': { label: 'X gömmeleri için satır içi CSS yok', help: 'Sade x kısa kodu için; stilini kendi CSS’inde ver.' },

  // Diller
  defaultContentLanguage: { label: 'Varsayılan dil', help: 'Ana dilin anahtarı. Birden fazla dil tanımlıysa bunlardan biriyle eşleşmeli.' },
  defaultContentLanguageInSubdir: { label: 'Varsayılan dil kendi klasöründe', help: 'Varsayılan dili de /tr/ (ya da benzeri) altında yayımlar.' },
  disableDefaultSiteRedirect: { label: 'Varsayılan siteye yönlendirme yok', help: '/ ile varsayılan dil klasörü arasındaki yönlendirmeyi yazmaz.' },
  disableDefaultLanguageRedirect: { label: 'Varsayılan dile yönlendirme yok (eski ad)', help: 'Üstteki ayarın eski adı.' },
  enableMissingTranslationPlaceholders: { label: 'Eksik çevirileri göster', help: 'Çeviri eksikse boş bırakmak yerine [i18n] kimlik gösterir.' },
  disableLanguages: { label: 'Kapalı diller', help: 'Atlanacak diller. Her dilin “Kapalı” anahtarını tercih et.' },
  'languages/*/label': { label: 'Ad', help: 'Dil seçicilerde gösterilir, ör. Türkçe. languageName’in yerini aldı.' },
  'languages/*/locale': { label: 'Yerel ayar', help: 'Çeviriler ve tarih biçimleri için dil etiketi, ör. tr-TR. languageCode’un yerini aldı.' },
  'languages/*/direction': { label: 'Yazı yönü', help: 'ltr ya da rtl (Arapça, Farsça, İbranice). languageDirection’ın yerini aldı.' },
  'languages/*/title': { label: 'Bu dilde site başlığı', help: 'Boşsa ana site başlığı kullanılır.' },
  'languages/*/weight': { label: 'Sıra', help: 'Dil listelerinde küçük olan önce gelir.' },
  'languages/*/disabled': { label: 'Kapalı', help: 'Derlerken bu dili atla.' },
  'languages/*/baseURL': { label: 'Bu dilin adresi', help: 'Dil başına ayrı alan adı. Bir dil ayarlarsa hepsi ayarlamalı.' },
  'languages/*/contentDir': { label: 'İçerik klasörü', help: '.tr.md dosya adları yerine bu dil için ayrı içerik klasörü.' },
  'languages/*/timeZone': { label: 'Saat dilimi', help: 'Bu dilin tarihleri için saat dilimi.' },

  // Derleme ve performans
  'minify/minifyOutput': { label: 'Çıktıyı küçült', help: 'HTML, CSS, JS, JSON, SVG ve XML’i küçültür; hugo --minify gibi.' },
  'minify/disableHTML': { label: 'HTML’i küçültme', help: 'HTML şablonların yazdığı gibi kalır.' },
  'minify/disableCSS': { label: 'CSS’i küçültme', help: 'CSS dosyaları değişmeden kalır.' },
  'minify/disableJS': { label: 'JavaScript’i küçültme', help: 'JavaScript değişmeden kalır.' },
  'minify/disableJSON': { label: 'JSON’u küçültme', help: 'JSON çıktısı değişmeden kalır.' },
  'minify/disableSVG': { label: 'SVG’yi küçültme', help: 'SVG dosyaları değişmeden kalır.' },
  'minify/disableXML': { label: 'XML’i küçültme', help: 'XML (RSS, site haritası) değişmeden kalır.' },
  'minify/tdewolff/html/keepComments': { label: 'HTML yorumlarını koru', help: 'Küçültülmüş HTML’de yorumlar kalır.' },
  'minify/tdewolff/html/keepWhitespace': { label: 'Boşlukları koru', help: 'HTML öğeleri arasındaki boşluklar kalır.' },
  timeout: { label: 'Sayfa işleme zaman aşımı', help: 'Bir sayfanın işlenmesi en fazla ne kadar sürebilir, ör. 60s ya da 2m. Yoğun görsel işlemede artır.' },
  publishDir: { label: 'Çıktı klasörü', help: 'Derlenen sitenin yazıldığı yer.' },
  'build/buildStats/enable': { label: 'hugo_stats.json yaz', help: 'Kullanılan HTML etiketlerini, sınıfları ve kimlikleri listeler; CSS temizliği (Tailwind) için.' },
  'build/buildStats/disableClasses': { label: 'Sınıfları istatistiğe katma', help: 'hugo_stats.json sınıflar olmadan yazılır.' },
  'build/buildStats/disableIDs': { label: 'Kimlikleri istatistiğe katma', help: 'hugo_stats.json kimlikler olmadan yazılır.' },
  'build/buildStats/disableTags': { label: 'Etiketleri istatistiğe katma', help: 'hugo_stats.json HTML etiketleri olmadan yazılır.' },
  'build/cleanDestinationDir/enable': {
    label: 'Çıktı klasörünü temizle',
    help: 'Çıktı klasöründe Hugo’nun üretmediği dosyaları siler; aşağıda korunmadıkça CNAME ya da _redirects gibi elle eklenmiş dosyalar da gider.',
  },
  'build/cleanDestinationDir/keepFiles': {
    label: 'Temizlikte korunacak dosyalar',
    help: 'Glob kalıpları; bunu ayarlamak varsayılanı siler, .git dosyaları için olan kalıbı koru. CNAME kullanıyorsan buraya ekle.',
  },
  'build/cleanDestinationDir/keepDirs': { label: 'Temizlikte korunacak klasörler', help: 'Glob kalıpları; varsayılan noktayla başlayan klasörleri korur.' },
  'build/useResourceCacheWhen': { label: 'Önbellekteki Sass çıktısını kullan', help: 'never, fallback (Sass yoksa) ya da always.' },
  'build/noJSConfigInAssets': { label: 'jsconfig.json yazma', help: 'js.Build assets/jsconfig.json dosyasını yazmaz.' },
  'build/cacheBusters': { label: 'Önbellek kırıcılar', help: 'source ile eşleşen bir dosya değişince target ile eşleşen önbellekteki kaynaklar yeniden üretilir.' },
  ignoreCache: { label: 'Dosya önbelleğini yok say', help: 'Her derlemede önbellekteki bütün kaynakları yeniden üretir.' },
  ignoreLogs: { label: 'Susturulan mesajlar', help: 'Gizlenecek mesaj kimlikleri (erroridf/warnidf).' },
  ignoreFiles: { label: 'Yok sayılan dosyalar', help: 'content, data ve i18n içinde atlanacak yolların düzenli ifadeleri.' },
  renderSegments: { label: 'Derlenecek bölümler', help: 'Yalnızca bu segment’leri derle; boşsa hepsi derlenir.' },
  noChmod: { label: 'İzinleri kopyalama', help: 'Çıktı dosyaları kaynak dosyanın izinlerini almaz.' },
  noTimes: { label: 'Değişiklik zamanlarını kopyalama', help: 'Çıktı dosyaları şimdiki zamanı alır.' },
  panicOnWarning: { label: 'İlk uyarıda dur', help: 'Her WARN’ı hata gibi ele alır.' },
  printI18nWarnings: { label: 'Eksik çevirileri bildir', help: 'Bir i18n metni eksikse uyarır.' },
  printPathWarnings: { label: 'Yol çakışmalarını bildir', help: 'İki dosya aynı yola yayımlanırsa uyarır.' },
  printUnusedTemplates: { label: 'Kullanılmayan şablonları bildir', help: 'Hiçbir sayfanın kullanmadığı şablonları listeler.' },
  templateMetrics: { label: 'Şablon süreleri', help: 'Her şablonun ne kadar sürdüğünü yazar.' },
  templateMetricsHints: { label: 'Şablon önbellek önerileri', help: 'İşe yarayacağı yerlerde partialCached önerir; şablon süreleri açık olmalı.' },

  // Geliştirme sunucusu
  'server/headers': { label: 'Yanıt başlıkları', help: 'Önizleme sunucusunun eşleşen yollar için gönderdiği başlıklar, ör. denemek için bir Content-Security-Policy.' },
  'server/redirects': {
    label: 'Yönlendirmeler',
    help: 'Önizleme sunucusu yönlendirmeleri. Herhangi birini tanımlamak yerleşik 404 kuralını siler; onu geri ekle.',
  },
  disableLiveReload: { label: 'Canlı yenileme yok', help: 'Önizleme bir değişiklikten sonra kendiliğinden yenilenmez.' },

  // Güvenlik
  'security/enableInlineShortcodes': { label: 'Satır içi kısa kodlar', help: 'İçeriğin şablon koduyla kısa kod tanımlamasına izin verir. Yalnızca tamamen güvenilen yazarlar için.' },
  'security/allowContent': {
    label: 'İzin verilen içerik türleri',
    help: 'content/ içinde izin verilen medya türleri. HTML ve Org dosyaları betik taşıyabildiği için varsayılan olarak reddedilir.',
  },
  'security/exec/allow': {
    label: 'Hugo’nun çalıştırabileceği programlar',
    help: 'Program adlarının düzenli ifadeleri. tailwindcss artık varsayılan listede değil (Hugo 0.165).',
  },
  'security/exec/osEnv': { label: 'Programlara geçen ortam', help: 'Harici araçların görebileceği ortam değişkenleri.' },
  'security/funcs/getenv': { label: 'Okunabilir ortam değişkenleri', help: 'Şablonların os.Getenv ile okuyabileceği değişkenler.' },
  'security/http/urls': {
    label: 'İzin verilen uzak adresler',
    help: 'resources.GetRemote’un indirebileceği adresler. Varsayılanı değiştirmek özel adreslere karşı denetimi de kapatır.',
  },
  'security/http/methods': { label: 'İzin verilen HTTP yöntemleri', help: 'resources.GetRemote’un kullanabileceği yöntemler.' },
  'security/http/mediaTypes': { label: 'Güvenilen yanıt türleri', help: 'Uzak sunuculardan kabul edilen içerik türleri.' },
  'security/http/proxyFromEnvironment': { label: 'Sistem vekil sunucusunu kullan', help: 'HTTP_PROXY, HTTPS_PROXY ve NO_PROXY’ye uyar.' },
  'security/node/permissions/disable': {
    label: 'Node araçlarını izin modeli olmadan çalıştır',
    help: 'Node araçları bu durumda dosyalarına tam erişir. Yalnızca Node sürümün 22’den eskiyse.',
  },
  'security/node/permissions/allowRead': { label: 'Node okuma izni', help: 'Node araçlarının okuyabileceği klasörler; . proje klasörüdür.' },
  'security/node/permissions/allowWrite': { label: 'Node yazma izni', help: 'Node araçlarının yazabileceği klasörler.' },
  'security/node/permissions/allowAddons': { label: 'Node yerel eklentileri', help: 'Yerel eklenti yükleyebilecek araçlar.' },
  'security/node/permissions/allowWorker': { label: 'Node işçi iş parçacıkları', help: 'İşçi iş parçacığı başlatabilecek araçlar.' },
  'security/node/permissions/allowChildProcess': { label: 'Node alt süreçleri', help: 'Başka program başlatabilecek araçlar.' },

  // Önbellekler ve modüller
  cacheDir: { label: 'Önbellek klasörü', help: 'Hugo’nun dosya önbelleklerini tuttuğu yer. Boşsa sistemin önbellek klasörü kullanılır.' },
  'caches/assets/dir': { label: 'İşlenmiş CSS önbellek klasörü', help: 'İşlenmiş CSS ve Sass’ın tutulduğu yer.' },
  'caches/assets/maxAge': { label: 'İşlenmiş CSS önbellek süresi', help: '24h gibi bir süre; -1 hiç dolmaz, 0 önbelleği kapatır.' },
  'caches/images/dir': { label: 'Görsel önbellek klasörü', help: 'Boyutlandırılmış ve dönüştürülmüş görsellerin tutulduğu yer.' },
  'caches/images/maxAge': { label: 'Görsel önbellek süresi', help: 'Süre; -1 hiç dolmaz, 0 önbelleği kapatır.' },
  'caches/getresource/dir': { label: 'Uzak kaynak önbellek klasörü', help: 'resources.GetRemote ile indirilen dosyaların tutulduğu yer.' },
  'caches/getresource/maxAge': { label: 'Uzak kaynak önbellek süresi', help: 'Süre; -1 hiç dolmaz, 0 her seferinde yeniden indirir.' },
  'caches/misc/dir': { label: 'Diğer önbellek klasörü', help: 'Diğer sonuçların (ör. matematik işleme) tutulduğu yer.' },
  'caches/misc/maxAge': { label: 'Diğer önbellek süresi', help: 'Süre; -1 hiç dolmaz, 0 önbelleği kapatır.' },
  'caches/modules/dir': { label: 'Modül önbellek klasörü', help: 'İndirilen modüllerin tutulduğu yer.' },
  'caches/modules/maxAge': { label: 'Modül önbellek süresi', help: 'Süre; -1 hiç dolmaz.' },
  'caches/modulegitinfo/dir': { label: 'Modül Git bilgisi önbellek klasörü', help: 'Modüllerin Git bilgisinin tutulduğu yer.' },
  'caches/modulegitinfo/maxAge': { label: 'Modül Git bilgisi önbellek süresi', help: 'Süre; varsayılan 24h.' },
  'caches/modulequeries/dir': { label: 'Modül sürüm önbellek klasörü', help: 'Modül sürüm sorgularının yanıtlarının tutulduğu yer.' },
  'caches/modulequeries/maxAge': { label: 'Modül sürüm önbellek süresi', help: 'Süre; varsayılan 24h.' },
  'HTTPCache/respectCacheControlNoStoreInRequest': { label: 'İsteklerdeki no-store’a uy', help: 'no-store işaretli uzak istekler önbelleğe alınmaz.' },
  'HTTPCache/respectCacheControlNoStoreInResponse': { label: 'Yanıtlardaki no-store’a uy', help: 'no-store işaretli yanıtlar önbelleğe alınmaz.' },
  'module/proxy': { label: 'Modül vekil sunucusu', help: 'Modül indirmek için GOPROXY; direct doğrudan kaynaktan indirir.' },
  'module/noProxy': { label: 'Vekilsiz modüller', help: 'Vekil sunucu olmadan indirilecek, virgülle ayrılmış kalıplar.' },
  'module/private': { label: 'Özel modüller', help: 'Özel olan modüllerin kalıpları (GOPRIVATE).' },
  'module/workspace': { label: 'Go çalışma alanı dosyası', help: 'Kullanılacak hugo.work dosyası ya da off.' },
  'module/replacements': { label: 'Modül değişimleri', help: 'Tema geliştirmek için: github.com/x/tema -> ../tema.' },
  'module/vendorClosest': { label: 'En yakın vendor kopyasını tercih et', help: 'Her modül için en yakın _vendor klasörünü kullan.' },
  'module/hugoVersion/min': { label: 'En düşük Hugo sürümü', help: 'Hugo bundan eskiyse uyarır.' },
  'module/hugoVersion/max': { label: 'En yüksek Hugo sürümü', help: 'Hugo bundan yeniyse uyarır.' },
  'module/imports': { label: 'İçe aktarılan modüller', help: 'Hugo modülü olarak içe aktarılan tema ve modüller. Ham dosyadan düzenle.' },
  'module/mounts': { label: 'Bağlamalar', help: 'Hangi klasörün content, layouts, static… olarak kullanılacağı. Birini tanımlamak o klasörün varsayılan bağlamasını kaldırır. Ham dosyadan düzenle.' },
}
