// Label and help text of every catalog key, by message id (`markup/goldmark/renderer/unsafe`).
// Registered as `settings.keys.<id>.label` / `.help` through ../messages.ts.

export const keyMessagesEn = {
  // Site identity
  title: { label: 'Site title', help: 'The name of the site, shown by most themes in the header and browser tab.' },
  baseURL: {
    label: 'Site address (baseURL)',
    help: 'The public address of the site with protocol and a trailing slash, e.g. https://example.com/. The preview server replaces it with localhost.',
  },
  locale: {
    label: 'Locale',
    help: 'Language tag such as tr or en-US. Picks translation files and formats dates and numbers. Replaces languageCode (Hugo 0.158).',
  },
  copyright: { label: 'Copyright notice', help: 'Text themes show in the footer, e.g. © 2026 Your Name.' },
  theme: { label: 'Theme', help: 'Theme folder in themes/ or a module path. With several themes, the first one wins.' },
  timeZone: {
    label: 'Time zone',
    help: 'IANA zone (e.g. Europe/Istanbul) used for dates written without an offset. Empty uses UTC.',
  },

  // URLs and permalinks
  permalinks: {
    label: 'Permalinks per section',
    help: 'URL pattern per section, e.g. posts → /:year/:month/:slug/. This short form applies to pages and terms.',
  },
  'permalinks/page': { label: 'Permalinks for pages', help: 'URL patterns for single pages, by section.' },
  'permalinks/section': { label: 'Permalinks for section lists', help: 'URL patterns for section list pages, by section.' },
  'permalinks/taxonomy': { label: 'Permalinks for taxonomy lists', help: 'URL patterns for pages that list all terms, e.g. /tags/.' },
  'permalinks/term': { label: 'Permalinks for terms', help: 'URL patterns for the page of one term, e.g. /tags/hugo/.' },
  removePathAccents: {
    label: 'Remove accents from URLs',
    help: 'Turns letters like ü, ş, ç into u, s, c in addresses made from file and section names (Gündem → gundem).',
  },
  uglyURLs: { label: 'Ugly URLs', help: 'Publish /posts/hello.html instead of /posts/hello/.' },
  disablePathToLower: { label: 'Keep capital letters in URLs', help: 'By default Hugo lower-cases every address.' },
  disableAliases: { label: 'No redirect pages for aliases', help: 'Do not write the HTML redirect files that front matter aliases normally create.' },
  relativeURLs: {
    label: 'Relative URLs',
    help: 'Rewrites root-relative links into page-relative ones. Only for sites opened straight from disk; it breaks many themes.',
  },
  canonifyURLs: {
    label: 'Absolute URLs (legacy)',
    help: 'Old post-processor that makes root-relative links absolute. Hugo may remove it; prefer absURL in templates.',
  },
  refLinksErrorLevel: { label: 'Broken ref/relref links', help: 'ERROR stops the build when a ref or relref link points nowhere; WARNING only reports it.' },
  refLinksNotFoundURL: { label: 'Address for broken ref links', help: 'Used in place of a ref or relref link that cannot be resolved.' },

  // Content
  summaryLength: { label: 'Summary length', help: 'Minimum number of words in an automatic summary.' },
  mainSections: {
    label: 'Main sections',
    help: 'Sections whose pages themes list on the home page. Empty: the section with the most pages.',
  },
  buildDrafts: { label: 'Publish drafts', help: 'Include pages with draft: true. Usually only wanted for the preview (config/development).' },
  buildFuture: { label: 'Publish future posts', help: 'Include pages whose publish date is in the future.' },
  buildExpired: { label: 'Publish expired pages', help: 'Include pages whose expiry date has passed.' },
  enableEmoji: { label: 'Emoji shortcodes', help: 'Turns :smile: style codes in content into emoji.' },
  disableKinds: {
    label: 'Page kinds not to build',
    help: 'For example taxonomy skips the /tags/ list page while term pages stay; sitemap skips sitemap.xml.',
  },
  enableGitInfo: { label: 'Use Git history', help: 'Reads the last commit of each page; with it, lastmod can come from Git. Needs git.' },
  hasCJKLanguage: { label: 'Chinese/Japanese/Korean text', help: 'Counts words correctly for summaries and reading time in CJK text.' },
  pluralizeListTitles: { label: 'Plural list titles', help: 'Makes automatic section titles plural (English rules only).' },
  capitalizeListTitles: { label: 'Capitalize list titles', help: 'Capitalizes automatic section, taxonomy and term titles.' },
  titleCaseStyle: { label: 'Title case style', help: 'How automatic titles are capitalized: ap, chicago, go, firstupper or none.' },
  defaultOutputFormat: { label: 'Default output format', help: 'Output format used when nothing else is set. Normally html.' },
  newContentEditor: { label: 'Editor for new content', help: 'Command that opens files created with hugo new content, e.g. code.' },
  'frontmatter/date': { label: 'Sources of the date', help: 'Front matter fields (and :filename, :fileModTime, :git) tried in order for a page’s date.' },
  'frontmatter/publishDate': { label: 'Sources of the publish date', help: 'Fields tried in order for the publish date.' },
  'frontmatter/lastmod': { label: 'Sources of the last-modified date', help: 'Fields tried in order for lastmod. :git needs Git history to be on.' },
  'frontmatter/expiryDate': { label: 'Sources of the expiry date', help: 'Fields tried in order for the expiry date.' },
  'page/nextPrevSortOrder': { label: 'Next/previous order', help: 'Direction of .Next and .Prev across the whole site.' },
  'page/nextPrevInSectionSortOrder': { label: 'Next/previous order in a section', help: 'Direction of .NextInSection and .PrevInSection.' },
  'related/threshold': { label: 'Related content threshold', help: '0–100; lower values find more (weaker) related pages.' },
  'related/includeNewer': { label: 'Include newer pages as related', help: 'By default only older pages are suggested as related.' },
  'related/toLower': { label: 'Ignore case for related content', help: 'Lower-cases keywords and tags before comparing them.' },
  'related/indices': {
    label: 'Related content indices',
    help: 'Front matter fields used to find related pages and their weights. Defining this list replaces the whole default.',
  },

  // Taxonomies
  taxonomies: {
    label: 'Taxonomies',
    help: 'Singular → plural, e.g. tag → tags. Defining the list replaces the defaults, so keep tag and category if you use them.',
  },
  sectionPagesMenu: { label: 'Menu for sections', help: 'Adds every top-level section to this menu automatically, e.g. main.' },

  // Markdown
  'markup/goldmark/renderer/unsafe': {
    label: 'Allow raw HTML in Markdown',
    help: 'Without it Hugo replaces HTML in posts with a comment. Turn it on only if you trust everyone who writes content.',
  },
  'markup/goldmark/renderer/hardWraps': { label: 'Line breaks as written', help: 'A single newline in a paragraph becomes a line break (<br>).' },
  'markup/goldmark/extensions/typographer/disable': {
    label: 'Turn off smart punctuation',
    help: 'Smart punctuation turns "quotes", -- and ... into typographic characters.',
  },
  'markup/goldmark/extensions/passthrough/enable': {
    label: 'Pass math through untouched',
    help: 'Keeps LaTeX between the delimiters below as written, for KaTeX or MathJax.',
  },
  'markup/goldmark/extensions/passthrough/delimiters/block': { label: 'Block math delimiters', help: 'Pairs such as \\[ … \\] and $$ … $$.' },
  'markup/goldmark/extensions/passthrough/delimiters/inline': { label: 'Inline math delimiters', help: 'Pairs such as \\( … \\).' },
  'markup/goldmark/parser/attribute/title': { label: 'Attributes on headings', help: 'Allows {#id .class} after a heading.' },
  'markup/goldmark/parser/attribute/block': { label: 'Attributes on blocks', help: 'Allows {.class} on paragraphs, lists, tables and other blocks.' },
  'markup/goldmark/parser/autoHeadingID': { label: 'Heading ids', help: 'Gives every heading an id so it can be linked to.' },
  'markup/goldmark/parser/autoIDType': { label: 'Heading id style', help: 'github keeps letters like ş; github-ascii drops them; blackfriday is the old style.' },
  'markup/goldmark/parser/autoDefinitionTermID': { label: 'Ids on definition terms', help: 'Gives definition list terms (<dt>) an id.' },
  'markup/goldmark/parser/wrapStandAloneImageWithinParagraph': {
    label: 'Wrap lone images in paragraphs',
    help: 'Turn off when an image render hook makes <figure> elements.',
  },
  'markup/goldmark/renderHooks/image/useEmbedded': {
    label: 'Built-in image hook',
    help: 'When Hugo’s own image render hook is used: auto, never, always, or fallback when the theme has none.',
  },
  'markup/goldmark/renderHooks/link/useEmbedded': { label: 'Built-in link hook', help: 'When Hugo’s own link render hook is used.' },
  'markup/goldmark/renderer/xhtml': { label: 'XHTML output', help: 'Writes self-closing tags such as <br />.' },
  'markup/goldmark/duplicateResourceFiles': {
    label: 'Copy shared resources per language',
    help: 'For multilingual sites: publish shared page resources once per language.',
  },
  'markup/goldmark/extensions/table': { label: 'Tables', help: 'GitHub-style tables with | columns.' },
  'markup/goldmark/extensions/strikethrough': { label: 'Strikethrough', help: '~~text~~ is struck through. Must be off when subscript is on.' },
  'markup/goldmark/extensions/taskList': { label: 'Task lists', help: '- [ ] and - [x] become checkboxes.' },
  'markup/goldmark/extensions/definitionList': { label: 'Definition lists', help: 'Term lines followed by : definition lines.' },
  'markup/goldmark/extensions/linkify': { label: 'Link bare URLs', help: 'Addresses written in text become links.' },
  'markup/goldmark/extensions/linkifyProtocol': { label: 'Protocol for www. links', help: 'Used when a bare link starts with www.' },
  'markup/goldmark/extensions/footnote/enable': { label: 'Footnotes', help: 'Text[^1] with [^1]: note below.' },
  'markup/goldmark/extensions/footnote/backlinkHTML': { label: 'Footnote back link', help: 'HTML of the link that jumps back from a footnote.' },
  'markup/goldmark/extensions/footnote/enableAutoIDPrefix': {
    label: 'Unique footnote ids',
    help: 'Prefixes footnote ids per page so several posts can share one list page.',
  },
  'markup/goldmark/extensions/typographer/leftDoubleQuote': { label: 'Opening double quote', help: 'Replacement for an opening ", e.g. &ldquo; or “.' },
  'markup/goldmark/extensions/typographer/rightDoubleQuote': { label: 'Closing double quote', help: 'Replacement for a closing ".' },
  'markup/goldmark/extensions/typographer/leftSingleQuote': { label: 'Opening single quote', help: 'Replacement for an opening \'.' },
  'markup/goldmark/extensions/typographer/rightSingleQuote': { label: 'Closing single quote', help: 'Replacement for a closing \'.' },
  'markup/goldmark/extensions/typographer/leftAngleQuote': { label: 'Opening angle quote', help: 'Replacement for <<, e.g. «.' },
  'markup/goldmark/extensions/typographer/rightAngleQuote': { label: 'Closing angle quote', help: 'Replacement for >>, e.g. ».' },
  'markup/goldmark/extensions/typographer/apostrophe': { label: 'Apostrophe', help: 'Replacement for an apostrophe inside a word.' },
  'markup/goldmark/extensions/typographer/enDash': { label: 'En dash', help: 'Replacement for --.' },
  'markup/goldmark/extensions/typographer/emDash': { label: 'Em dash', help: 'Replacement for ---.' },
  'markup/goldmark/extensions/typographer/ellipsis': { label: 'Ellipsis', help: 'Replacement for ....' },
  'markup/goldmark/extensions/extras/delete/enable': { label: 'Deleted text (~~)', help: '~~text~~ becomes <del>.' },
  'markup/goldmark/extensions/extras/insert/enable': { label: 'Inserted text (++)', help: '++text++ becomes <ins>.' },
  'markup/goldmark/extensions/extras/mark/enable': { label: 'Highlighted text (==)', help: '==text== becomes <mark>.' },
  'markup/goldmark/extensions/extras/subscript/enable': { label: 'Subscript', help: 'H~2~O. Turn strikethrough off when you use it.' },
  'markup/goldmark/extensions/extras/superscript/enable': { label: 'Superscript', help: '1^st^.' },
  'markup/goldmark/extensions/cjk/enable': { label: 'CJK extension', help: 'Line breaking rules for Chinese, Japanese and Korean.' },
  'markup/goldmark/extensions/cjk/eastAsianLineBreaks': { label: 'East Asian line breaks', help: 'No space is added where a line breaks between CJK characters.' },
  'markup/goldmark/extensions/cjk/eastAsianLineBreaksStyle': { label: 'Line break style', help: 'simple or css3draft.' },
  'markup/goldmark/extensions/cjk/escapedSpace': { label: 'Escaped spaces', help: 'A backslash before a space removes the space.' },
  'markup/defaultMarkdownHandler': {
    label: 'Markdown renderer',
    help: 'goldmark is built in. The others need an external program and security.exec.allow.',
  },

  // Syntax highlighting
  'markup/highlight/style': { label: 'Code color style', help: 'One of the 74 Chroma styles. Dark and light pairs exist, e.g. github and github-dark.' },
  'markup/highlight/lineNos': { label: 'Line numbers', help: 'Show line numbers in code blocks: inline, in a table, or not at all.' },
  'markup/highlight/noClasses': {
    label: 'Inline colors',
    help: 'Colors go into the HTML. Turn off to use CSS classes (hugo gen chromastyles) and follow the light/dark theme.',
  },
  'markup/highlight/codeFences': { label: 'Highlight code fences', help: 'Colors ``` blocks.' },
  'markup/highlight/guessSyntax': { label: 'Guess the language', help: 'Colors code blocks without a language by guessing it.' },
  'markup/highlight/lineNumbersInTable': { label: 'Line numbers in a table', help: 'Puts numbers in a separate column so copying skips them.' },
  'markup/highlight/lineNoStart': { label: 'First line number', help: 'Number of the first line.' },
  'markup/highlight/anchorLineNos': { label: 'Line number anchors', help: 'Line numbers become links to that line.' },
  'markup/highlight/lineAnchors': { label: 'Line anchor prefix', help: 'Prefix of line anchor ids, useful with several blocks on a page.' },
  'markup/highlight/hl_Lines': { label: 'Lines to highlight', help: 'For example 2-4 7. Usually set per block.' },
  'markup/highlight/hl_inline': { label: 'No wrapper element', help: 'Highlights without the surrounding container.' },
  'markup/highlight/tabWidth': { label: 'Tab width', help: 'Spaces per tab; only with inline colors.' },
  'markup/highlight/wrapperClass': { label: 'Wrapper class', help: 'CSS class of the element around code blocks.' },

  // Table of contents
  'markup/tableOfContents/startLevel': { label: 'First heading level', help: 'Smallest heading level in the table of contents (2 = ##).' },
  'markup/tableOfContents/endLevel': { label: 'Last heading level', help: 'Deepest heading level included; at least the first level.' },
  'markup/tableOfContents/ordered': { label: 'Numbered list', help: 'Uses a numbered list (<ol>) instead of bullets.' },

  // SEO
  enableRobotsTXT: { label: 'Create robots.txt', help: 'Writes /robots.txt. The built-in one allows everything; a theme or layouts/robots.txt can change it.' },
  'sitemap/changeFreq': { label: 'Sitemap change frequency', help: 'Default changefreq for every page; empty leaves it out.' },
  'sitemap/priority': { label: 'Sitemap priority', help: '0.0–1.0; -1 leaves it out.' },
  'sitemap/filename': { label: 'Sitemap file name', help: 'Name of the sitemap file.' },
  'sitemap/disable': { label: 'Leave pages out of the sitemap', help: 'Mostly set per page in front matter. To drop the sitemap, add sitemap to the page kinds not to build.' },
  disableHugoGeneratorInject: { label: 'No generator tag', help: 'Leaves out <meta name="generator" content="Hugo …"> on the home page.' },

  // Outputs
  'outputs/home': { label: 'Home page outputs', help: 'Files built for the home page. The first is the main one; add llms for /llms.txt.' },
  'outputs/page': { label: 'Page outputs', help: 'Files built for each single page.' },
  'outputs/section': { label: 'Section outputs', help: 'Files built for section list pages (html, rss…).' },
  'outputs/taxonomy': { label: 'Taxonomy list outputs', help: 'Files built for pages that list all terms.' },
  'outputs/term': { label: 'Term outputs', help: 'Files built for the page of each term.' },
  outputFormats: {
    label: 'Custom output formats',
    help: 'New or changed formats, e.g. llms (text/plain, baseName llms). Built-in formats stay available.',
  },
  mediaTypes: { label: 'Media types', help: 'Extra or changed media types and their file suffixes.' },

  // Pagination
  'pagination/pagerSize': { label: 'Items per page', help: 'Number of items on each page of a paginated list. Replaces paginate.' },
  'pagination/path': { label: 'Page path segment', help: 'The word in /page/2/; Turkish sites often use sayfa. Replaces paginatePath.' },
  'pagination/disableAliases': { label: 'No redirect for page 1', help: 'Do not redirect /page/1/ to the list itself.' },

  // Images
  'imaging/jpeg/quality': { label: 'JPEG quality', help: '1–100. Higher is sharper and larger.' },
  'imaging/webp/quality': { label: 'WebP quality', help: '1–100, for lossy WebP.' },
  'imaging/avif/quality': { label: 'AVIF quality', help: '1–100. AVIF 60 looks about like JPEG 75.' },
  'imaging/anchor': { label: 'Crop focus', help: 'Which part of an image Fill and Crop keep. Smart looks for the interesting area.' },
  'imaging/resampleFilter': { label: 'Resize filter', help: 'box is fast; lanczos and catmullRom are sharper but slower.' },
  'imaging/bgColor': { label: 'Background color', help: 'Fills transparent areas when converting to a format without transparency.' },
  'imaging/webp/compression': { label: 'WebP compression', help: 'lossy or lossless.' },
  'imaging/webp/hint': { label: 'WebP image type', help: 'Tunes the encoder: photo, picture, drawing, icon or text.' },
  'imaging/webp/method': { label: 'WebP effort', help: '0–6; higher is smaller but slower.' },
  'imaging/webp/useSharpYuv': { label: 'Sharper WebP colors', help: 'More accurate color conversion, slower.' },
  'imaging/avif/compression': { label: 'AVIF compression', help: 'lossy or lossless.' },
  'imaging/avif/hint': { label: 'AVIF image type', help: 'photo and picture use smaller color data; the others keep full color.' },
  'imaging/avif/encoderSpeed': { label: 'AVIF speed', help: '1–10; lower is smaller but much slower (below 5 is very slow).' },
  'imaging/meta/sources': { label: 'Metadata sources', help: 'Where .Meta reads image metadata from: exif, iptc, xmp.' },
  'imaging/meta/fields': { label: 'Metadata fields', help: 'Glob patterns of fields to read; the default leaves out GPS and camera details.' },

  // Privacy
  'privacy/disqus/disable': { label: 'Turn off Disqus', help: 'Disables Hugo’s built-in Disqus template.' },
  'privacy/googleAnalytics/disable': { label: 'Turn off Google Analytics', help: 'Disables Hugo’s built-in Google Analytics template.' },
  'privacy/googleAnalytics/respectDoNotTrack': { label: 'Respect Do Not Track', help: 'No analytics for visitors who ask not to be tracked (default since Hugo 0.153).' },
  'privacy/instagram/disable': { label: 'Turn off Instagram', help: 'Disables the instagram shortcode.' },
  'privacy/instagram/simple': { label: 'Simple Instagram embeds', help: 'A static card without Instagram’s script.' },
  'privacy/vimeo/disable': { label: 'Turn off Vimeo', help: 'Disables the vimeo shortcode.' },
  'privacy/vimeo/enableDNT': { label: 'Vimeo without tracking', help: 'Asks Vimeo not to track viewers.' },
  'privacy/vimeo/simple': { label: 'Simple Vimeo embeds', help: 'A thumbnail link instead of the player.' },
  'privacy/x/disable': { label: 'Turn off X (Twitter)', help: 'Disables the x shortcode.' },
  'privacy/x/enableDNT': { label: 'X without tracking', help: 'Asks X not to use the embed for tracking.' },
  'privacy/x/simple': { label: 'Simple X embeds', help: 'Static post without X’s script.' },
  'privacy/youTube/disable': { label: 'Turn off YouTube', help: 'Disables the youtube shortcode.' },
  'privacy/youTube/privacyEnhanced': { label: 'YouTube privacy mode', help: 'Embeds from youtube-nocookie.com.' },

  // Services
  'services/googleAnalytics/id': { label: 'Google Analytics ID', help: 'G-XXXXXXXXXX tag for the built-in template. Often set only for production.' },
  'services/disqus/shortname': { label: 'Disqus shortname', help: 'Your site’s name on Disqus, for the built-in comments template.' },
  'services/rss/limit': { label: 'RSS item limit', help: 'Maximum number of items in feeds; -1 means all.' },
  'services/x/disableInlineCSS': { label: 'No inline CSS for X embeds', help: 'For the simple x shortcode; style it in your own CSS.' },

  // Languages
  defaultContentLanguage: { label: 'Default language', help: 'Language key of the main language. Must match one of the languages when several are defined.' },
  defaultContentLanguageInSubdir: { label: 'Default language in its own folder', help: 'Publishes the default language under /tr/ (or similar) too.' },
  disableDefaultSiteRedirect: { label: 'No redirect to the default site', help: 'Skips the redirect between / and the default language folder.' },
  disableDefaultLanguageRedirect: { label: 'No default language redirect (old name)', help: 'Old name of the setting above.' },
  enableMissingTranslationPlaceholders: { label: 'Show missing translations', help: 'Shows [i18n] id where a translation is missing instead of leaving it empty.' },
  disableLanguages: { label: 'Disabled languages', help: 'Languages to skip. Prefer the Disabled switch of each language.' },
  'languages/*/label': { label: 'Name', help: 'Shown in language switchers, e.g. Türkçe. Replaces languageName.' },
  'languages/*/locale': { label: 'Locale', help: 'Language tag for translations and date formats, e.g. tr-TR. Replaces languageCode.' },
  'languages/*/direction': { label: 'Text direction', help: 'ltr or rtl (Arabic, Persian, Hebrew). Replaces languageDirection.' },
  'languages/*/title': { label: 'Site title in this language', help: 'Empty uses the main site title.' },
  'languages/*/weight': { label: 'Order', help: 'Smaller comes first in language lists.' },
  'languages/*/disabled': { label: 'Disabled', help: 'Skip this language when building.' },
  'languages/*/baseURL': { label: 'Address of this language', help: 'Own domain per language. If one language sets it, every language must.' },
  'languages/*/contentDir': { label: 'Content folder', help: 'Separate content folder for this language instead of .tr.md file names.' },
  'languages/*/timeZone': { label: 'Time zone', help: 'Time zone for this language’s dates.' },

  // Build and performance
  'minify/minifyOutput': { label: 'Minify output', help: 'Makes HTML, CSS, JS, JSON, SVG and XML smaller, like hugo --minify.' },
  'minify/disableHTML': { label: 'Do not minify HTML', help: 'Leaves HTML as the templates write it.' },
  'minify/disableCSS': { label: 'Do not minify CSS', help: 'Leaves CSS files unchanged.' },
  'minify/disableJS': { label: 'Do not minify JavaScript', help: 'Leaves JavaScript unchanged.' },
  'minify/disableJSON': { label: 'Do not minify JSON', help: 'Leaves JSON output unchanged.' },
  'minify/disableSVG': { label: 'Do not minify SVG', help: 'Leaves SVG files unchanged.' },
  'minify/disableXML': { label: 'Do not minify XML', help: 'Leaves XML (RSS, sitemap) unchanged.' },
  'minify/tdewolff/html/keepComments': { label: 'Keep HTML comments', help: 'Comments stay in minified HTML.' },
  'minify/tdewolff/html/keepWhitespace': { label: 'Keep whitespace', help: 'Keeps spaces between HTML elements.' },
  timeout: { label: 'Render timeout', help: 'How long a page may take to render, e.g. 60s or 2m. Raise it for heavy image processing.' },
  publishDir: { label: 'Output folder', help: 'Where the built site is written.' },
  'build/buildStats/enable': { label: 'Write hugo_stats.json', help: 'Lists used HTML tags, classes and ids, for CSS purging (Tailwind).' },
  'build/buildStats/disableClasses': { label: 'Leave classes out of the stats', help: 'hugo_stats.json without CSS classes.' },
  'build/buildStats/disableIDs': { label: 'Leave ids out of the stats', help: 'hugo_stats.json without ids.' },
  'build/buildStats/disableTags': { label: 'Leave tags out of the stats', help: 'hugo_stats.json without HTML tags.' },
  'build/cleanDestinationDir/enable': {
    label: 'Clean the output folder',
    help: 'Deletes files in the output folder that Hugo did not create, including hand-added files such as CNAME or _redirects unless they are kept below.',
  },
  'build/cleanDestinationDir/keepFiles': {
    label: 'Files to keep when cleaning',
    help: 'Glob patterns; setting this replaces the default, so keep its pattern for .git files. Add CNAME here if you publish one.',
  },
  'build/cleanDestinationDir/keepDirs': { label: 'Folders to keep when cleaning', help: 'Glob patterns; the default keeps dot-folders.' },
  'build/useResourceCacheWhen': { label: 'Use cached Sass output', help: 'never, fallback (when Sass is missing) or always.' },
  'build/noJSConfigInAssets': { label: 'No jsconfig.json', help: 'js.Build will not write assets/jsconfig.json.' },
  'build/cacheBusters': { label: 'Cache busters', help: 'When a file matching source changes, cached resources matching target are rebuilt.' },
  ignoreCache: { label: 'Ignore the file cache', help: 'Rebuilds every cached resource on each build.' },
  ignoreLogs: { label: 'Silenced messages', help: 'Message ids (from erroridf/warnidf) to hide.' },
  ignoreFiles: { label: 'Ignored files', help: 'Regular expressions of paths to skip in content, data and i18n.' },
  renderSegments: { label: 'Segments to render', help: 'Build only these segments; empty builds everything.' },
  noChmod: { label: 'Do not copy permissions', help: 'Output files do not get the source file permissions.' },
  noTimes: { label: 'Do not copy modification times', help: 'Output files get the current time.' },
  panicOnWarning: { label: 'Stop on the first warning', help: 'Treats every WARN as an error.' },
  printI18nWarnings: { label: 'Report missing translations', help: 'Warns when an i18n string is missing.' },
  printPathWarnings: { label: 'Report path clashes', help: 'Warns when two files publish to the same path.' },
  printUnusedTemplates: { label: 'Report unused templates', help: 'Lists templates no page uses.' },
  templateMetrics: { label: 'Template timings', help: 'Prints how long each template took.' },
  templateMetricsHints: { label: 'Template caching hints', help: 'Suggests partialCached where it helps; needs template timings.' },

  // Development server
  'server/headers': { label: 'Response headers', help: 'Headers the preview server sends for matching paths, e.g. a Content-Security-Policy to test.' },
  'server/redirects': {
    label: 'Redirects',
    help: 'Preview server redirects and rewrites. Defining any replaces the built-in 404 rule, so add it back.',
  },
  disableLiveReload: { label: 'No live reload', help: 'The preview does not refresh by itself after a change.' },

  // Security
  'security/enableInlineShortcodes': { label: 'Inline shortcodes', help: 'Lets content define shortcodes with template code. Only for fully trusted authors.' },
  'security/allowContent': {
    label: 'Allowed content types',
    help: 'Media types allowed in content/. HTML and Org files are refused by default because they can carry scripts.',
  },
  'security/exec/allow': {
    label: 'Programs Hugo may run',
    help: 'Regular expressions of executable names. tailwindcss is no longer in the default list (Hugo 0.165).',
  },
  'security/exec/osEnv': { label: 'Environment passed to programs', help: 'Environment variables external tools may see.' },
  'security/funcs/getenv': { label: 'Readable environment variables', help: 'Variables templates may read with os.Getenv.' },
  'security/http/urls': {
    label: 'Allowed remote URLs',
    help: 'Addresses resources.GetRemote may fetch. Changing the default also turns off the check against private addresses.',
  },
  'security/http/methods': { label: 'Allowed HTTP methods', help: 'Methods resources.GetRemote may use.' },
  'security/http/mediaTypes': { label: 'Trusted response types', help: 'Content types accepted from remote servers.' },
  'security/http/proxyFromEnvironment': { label: 'Use the system proxy', help: 'Honors HTTP_PROXY, HTTPS_PROXY and NO_PROXY.' },
  'security/node/permissions/disable': {
    label: 'Run Node tools without the permission model',
    help: 'Node tools then have full access to your files. Only if your Node is older than 22.',
  },
  'security/node/permissions/allowRead': { label: 'Node read access', help: 'Folders Node tools may read; . is the project.' },
  'security/node/permissions/allowWrite': { label: 'Node write access', help: 'Folders Node tools may write.' },
  'security/node/permissions/allowAddons': { label: 'Node native add-ons', help: 'Tools allowed to load native add-ons.' },
  'security/node/permissions/allowWorker': { label: 'Node worker threads', help: 'Tools allowed to start worker threads.' },
  'security/node/permissions/allowChildProcess': { label: 'Node child processes', help: 'Tools allowed to start other programs.' },

  // Caches and modules
  cacheDir: { label: 'Cache folder', help: 'Where Hugo keeps its file caches. Empty uses the system cache folder.' },
  'caches/assets/dir': { label: 'Processed CSS cache folder', help: 'Where processed CSS and Sass are kept.' },
  'caches/assets/maxAge': { label: 'Processed CSS cache lifetime', help: 'Duration such as 24h; -1 never expires, 0 turns the cache off.' },
  'caches/images/dir': { label: 'Image cache folder', help: 'Where resized and converted images are kept.' },
  'caches/images/maxAge': { label: 'Image cache lifetime', help: 'Duration; -1 never expires, 0 turns the cache off.' },
  'caches/getresource/dir': { label: 'Remote resource cache folder', help: 'Where files fetched with resources.GetRemote are kept.' },
  'caches/getresource/maxAge': { label: 'Remote resource cache lifetime', help: 'Duration; -1 never expires, 0 fetches every time.' },
  'caches/misc/dir': { label: 'Other cache folder', help: 'Where other results (e.g. math rendering) are kept.' },
  'caches/misc/maxAge': { label: 'Other cache lifetime', help: 'Duration; -1 never expires, 0 turns the cache off.' },
  'caches/modules/dir': { label: 'Module cache folder', help: 'Where downloaded modules are kept.' },
  'caches/modules/maxAge': { label: 'Module cache lifetime', help: 'Duration; -1 never expires.' },
  'caches/modulegitinfo/dir': { label: 'Module Git info cache folder', help: 'Where Git information of modules is kept.' },
  'caches/modulegitinfo/maxAge': { label: 'Module Git info cache lifetime', help: 'Duration; the default is 24h.' },
  'caches/modulequeries/dir': { label: 'Module version cache folder', help: 'Where answers to module version queries are kept.' },
  'caches/modulequeries/maxAge': { label: 'Module version cache lifetime', help: 'Duration; the default is 24h.' },
  'HTTPCache/respectCacheControlNoStoreInRequest': { label: 'Honor no-store in requests', help: 'Remote requests marked no-store are not cached.' },
  'HTTPCache/respectCacheControlNoStoreInResponse': { label: 'Honor no-store in responses', help: 'Responses marked no-store are not cached.' },
  'module/proxy': { label: 'Module proxy', help: 'GOPROXY for downloading modules; direct fetches from the source.' },
  'module/noProxy': { label: 'Modules without proxy', help: 'Comma-separated patterns fetched without the proxy.' },
  'module/private': { label: 'Private modules', help: 'Patterns of modules that are private (GOPRIVATE).' },
  'module/workspace': { label: 'Go workspace file', help: 'A hugo.work file to use, or off.' },
  'module/replacements': { label: 'Module replacements', help: 'For theme development: github.com/x/theme -> ../theme.' },
  'module/vendorClosest': { label: 'Prefer the closest vendored copy', help: 'Use the nearest _vendor folder for each module.' },
  'module/hugoVersion/min': { label: 'Minimum Hugo version', help: 'Hugo warns when it is older than this.' },
  'module/hugoVersion/max': { label: 'Maximum Hugo version', help: 'Hugo warns when it is newer than this.' },
  'module/imports': { label: 'Imported modules', help: 'Themes and modules imported as Hugo modules. Edit them in the raw file.' },
  'module/mounts': { label: 'Mounts', help: 'Which folders map to content, layouts, static…. Defining one removes that folder’s default mount. Edit them in the raw file.' },
}
