// Blowfish (github.com/nunocoracao/blowfish). Defaults and comments come from the theme's own
// config/_default/params.toml at run time; this profile adds labels, groups and actions.
// Docs: https://blowfish.page/docs/configuration/#theme-parameters
import { L, type SchemaField, type ThemeSchema } from '../schema'

const bool = (group: string, en: string, tr: string, def: boolean, extra: SchemaField = {}): SchemaField => ({
  type: 'boolean',
  default: def,
  'x-group': group,
  'x-label': L(en, tr),
  ...extra,
})
const text = (group: string, en: string, tr: string, extra: SchemaField = {}): SchemaField => ({
  type: 'string',
  'x-group': group,
  'x-label': L(en, tr),
  ...extra,
})
const HERO_STYLES = ['basic', 'big', 'background', 'thumbAndBackground']

const listLike = (group: string): Record<string, SchemaField> => ({
  showHero: bool(group, 'Show hero image', 'Büyük görseli göster', false),
  heroStyle: { type: 'string', enum: HERO_STYLES, 'x-group': group, 'x-label': L('Hero style', 'Büyük görsel stili') },
  showBreadcrumbs: bool(group, 'Show breadcrumbs', 'Sayfa yolunu göster', false),
  showViews: bool(group, 'Show views (Firebase)', 'Görüntülenmeyi göster (Firebase)', false),
  showLikes: bool(group, 'Show likes (Firebase)', 'Beğenileri göster (Firebase)', false),
  showTableOfContents: bool(group, 'Show table of contents', 'İçindekileri göster', false),
  cardView: bool(group, 'Card view', 'Kart görünümü', false),
})

export const blowfish: ThemeSchema = {
  'x-theme': {
    id: 'blowfish',
    name: 'Blowfish',
    repos: ['github.com/nunocoracao/blowfish'],
    themeTomlNames: ['Blowfish'],
    folderNames: ['blowfish', 'hugo-blowfish'],
    fingerprint: ['assets/css/schemes/blowfish.css', 'config/_default/params.toml'],
    docs: 'https://blowfish.page/docs/configuration/',
    cssHook: { kind: 'file', path: 'assets/css/custom.css' },
    cssVarsFiles: ['assets/css/schemes/{params.colorScheme|blowfish}.css'],
    darkSelector: '.dark',
  },
  'x-groups': [
    { id: 'general', label: L('General', 'Genel') },
    { id: 'appearance', label: L('Appearance', 'Görünüm') },
    { id: 'images', label: L('Images', 'Görseller') },
    { id: 'header', label: L('Header', 'Üst bölüm') },
    { id: 'footer', label: L('Footer', 'Alt bilgi') },
    { id: 'homepage', label: L('Home page', 'Ana sayfa') },
    { id: 'article', label: L('Articles', 'Yazılar') },
    { id: 'list', label: L('Lists', 'Listeler') },
    { id: 'taxonomy', label: L('Taxonomy pages', 'Sınıflandırma sayfaları') },
    { id: 'term', label: L('Term pages', 'Terim sayfaları') },
    { id: 'analytics', label: L('Analytics and verification', 'Analiz ve doğrulama') },
  ],
  type: 'object',
  properties: {
    colorScheme: {
      type: 'string',
      enum: [
        'blowfish',
        'avocado',
        'fire',
        'ocean',
        'forest',
        'princess',
        'neon',
        'bloody',
        'terminal',
        'marvel',
        'noir',
        'autumn',
        'congo',
        'slate',
        'github',
        'one-light',
        'burufugu',
      ],
      default: 'blowfish',
      'x-allowCustom': true,
      'x-group': 'appearance',
      'x-label': L('Colour scheme', 'Renk şeması'),
      'x-description': L('A file in assets/css/schemes/.', 'assets/css/schemes/ içindeki bir dosya.'),
    },
    defaultAppearance: {
      type: 'string',
      enum: ['light', 'dark'],
      default: 'light',
      'x-group': 'appearance',
      'x-label': L('Default appearance', 'Varsayılan görünüm'),
    },
    autoSwitchAppearance: bool('appearance', "Follow the visitor's system", 'Ziyaretçinin sistemine uy', true),
    enableA11y: bool('appearance', 'Accessibility panel', 'Erişilebilirlik paneli', false),
    enableStyledScrollbar: bool('appearance', 'Styled scroll bars', 'Stilli kaydırma çubukları', true),
    highlightCurrentMenuArea: bool('appearance', 'Highlight the current menu item', 'Geçerli menü öğesini vurgula', false),
    smartTOC: bool('appearance', 'Smart table of contents', 'Akıllı içindekiler', false),
    enableSearch: bool('general', 'Site search', 'Site içi arama', true, {
      'x-requiresConfig': {
        path: 'outputs.home',
        value: 'JSON',
        note: L('Search needs JSON in outputs.home.', 'Arama için outputs.home içinde JSON gerekir.'),
      },
    }),
    enableCodeCopy: bool('general', 'Copy buttons on code blocks', 'Kod bloklarında kopyala düğmesi', false),
    enableStructuredBreadcrumbs: bool('general', 'Structured data breadcrumbs', 'Yapısal veri sayfa yolu', false),
    replyByEmail: bool('general', 'Reply by email link', 'E-postayla yanıt bağlantısı', false),
    mainSections: { type: 'array', items: { type: 'string' }, 'x-group': 'general', 'x-label': L('Main sections', 'Ana bölümler') },
    robots: text('general', 'Robots meta tag', 'Robots meta etiketi'),
    fingerprintAlgorithm: {
      type: 'string',
      enum: ['sha512', 'sha384', 'sha256'],
      default: 'sha512',
      'x-group': 'general',
      'x-label': L('Fingerprint algorithm', 'Parmak izi algoritması'),
    },
    disableImageOptimization: bool('images', 'Turn off image optimisation', 'Görsel optimizasyonunu kapat', false),
    disableImageOptimizationMD: bool('images', 'Turn off optimisation of images in Markdown', 'Markdown görsellerinin optimizasyonunu kapat', false),
    disableTextInHeader: bool('header', 'No text next to the logo', 'Logonun yanında metin olmasın', false),
    defaultBackgroundImage: text('images', 'Default background image', 'Varsayılan arka plan görseli', { format: 'image', 'x-widget': 'image' }),
    defaultFeaturedImage: text('images', 'Default featured image', 'Varsayılan öne çıkan görsel', { format: 'image', 'x-widget': 'image' }),
    defaultSocialImage: text('images', 'Default share image', 'Varsayılan paylaşım görseli', { format: 'image', 'x-widget': 'image' }),
    hotlinkFeatureImage: bool('images', 'Use featured images as links', 'Öne çıkan görselleri bağlantı olarak kullan', false),
    backgroundImageWidth: { type: 'integer', 'x-group': 'images', 'x-label': L('Background image width', 'Arka plan görseli genişliği') },
    imagePosition: text('images', 'Image position', 'Görsel konumu', { 'x-placeholder': '50% 50%' }),
    header: {
      type: 'object',
      'x-group': 'header',
      properties: {
        layout: {
          type: 'string',
          enum: ['basic', 'fixed', 'fixed-fill', 'fixed-gradient', 'fixed-fill-blur', 'floating'],
          default: 'basic',
          'x-group': 'header',
          'x-label': L('Header layout', 'Üst bölüm düzeni'),
        },
      },
    },
    footer: {
      type: 'object',
      'x-group': 'footer',
      properties: {
        showMenu: bool('footer', 'Footer menu', 'Alt menü', true),
        showCopyright: bool('footer', 'Copyright', 'Telif satırı', true),
        showThemeAttribution: bool('footer', 'Theme credit', 'Tema künyesi', true),
        showAppearanceSwitcher: bool('footer', 'Light/dark switch', 'Açık/koyu düğmesi', true),
        showScrollToTop: bool('footer', '"Back to top" button', '"Başa dön" düğmesi', true),
      },
    },
    homepage: {
      type: 'object',
      'x-group': 'homepage',
      properties: {
        layout: {
          type: 'string',
          enum: ['page', 'profile', 'hero', 'card', 'background', 'landing', 'custom'],
          default: 'profile',
          'x-group': 'homepage',
          'x-label': L('Home page layout', 'Ana sayfa düzeni'),
        },
        homepageImage: text('homepage', 'Home page image', 'Ana sayfa görseli', { format: 'image', 'x-widget': 'image' }),
        showRecent: bool('homepage', 'Show recent posts', 'Son yazıları göster', false),
        showRecentItems: { type: 'integer', default: 5, minimum: 1, 'x-group': 'homepage', 'x-label': L('Number of recent posts', 'Son yazı sayısı') },
        showMoreLink: bool('homepage', '"Show more" link', '"Daha fazla" bağlantısı', false),
        showMoreLinkDest: text('homepage', '"Show more" address', '"Daha fazla" adresi', { default: '/posts/', 'x-widget': 'url' }),
        cardView: bool('homepage', 'Card view', 'Kart görünümü', false),
        layoutBackgroundBlur: bool('homepage', 'Blur the background', 'Arka planı bulanıklaştır', false),
      },
    },
    article: {
      type: 'object',
      'x-group': 'article',
      properties: {
        showDate: bool('article', 'Date', 'Tarih', true),
        showDateUpdated: bool('article', 'Last updated date', 'Son güncelleme tarihi', false),
        showAuthor: bool('article', 'Author', 'Yazar', true),
        showHero: bool('article', 'Hero image', 'Büyük görsel', false),
        heroStyle: { type: 'string', enum: HERO_STYLES, 'x-group': 'article', 'x-label': L('Hero style', 'Büyük görsel stili') },
        showBreadcrumbs: bool('article', 'Breadcrumbs', 'Sayfa yolu', false),
        showDraftLabel: bool('article', 'Draft label', 'Taslak etiketi', true),
        showEdit: bool('article', 'Edit link', 'Düzenleme bağlantısı', false),
        editURL: text('article', 'Edit address', 'Düzenleme adresi', { format: 'uri', 'x-widget': 'url' }),
        editAppendPath: bool('article', 'Append the file path', 'Dosya yolunu ekle', true),
        seriesOpened: bool('article', 'Series box open', 'Seri kutusu açık', false),
        showHeadingAnchors: bool('article', 'Heading anchors', 'Başlık bağlantıları', true),
        showPagination: bool('article', 'Previous/next links', 'Önceki/sonraki bağlantıları', true),
        invertPagination: bool('article', 'Invert previous/next', 'Önceki/sonrakini ters çevir', false),
        showReadingTime: bool('article', 'Reading time', 'Okuma süresi', true),
        showReadingProgress: bool('article', 'Reading progress bar', 'Okuma ilerleme çubuğu', false),
        showTableOfContents: bool('article', 'Table of contents', 'İçindekiler', false),
        showRelatedContent: bool('article', 'Related posts', 'İlgili yazılar', false),
        relatedContentLimit: { type: 'integer', default: 3, minimum: 1, 'x-group': 'article', 'x-label': L('Related posts limit', 'İlgili yazı sayısı') },
        showTaxonomies: bool('article', 'Taxonomies', 'Sınıflandırmalar', false),
        showCategories: bool('article', 'Categories', 'Kategoriler', true),
        showTags: bool('article', 'Tags', 'Etiketler', true),
        showWordCount: bool('article', 'Word count', 'Kelime sayısı', true),
        showZenMode: bool('article', 'Zen mode button', 'Zen modu düğmesi', false),
        showViews: bool('article', 'Views (Firebase)', 'Görüntülenme (Firebase)', false),
        showLikes: bool('article', 'Likes (Firebase)', 'Beğeniler (Firebase)', false),
        sharingLinks: {
          type: 'array',
          items: {
            type: 'string',
            enum: ['linkedin', 'twitter', 'bluesky', 'mastodon', 'reddit', 'pinterest', 'facebook', 'email', 'whatsapp', 'telegram', 'line'],
          },
          'x-widget': 'multiselect',
          'x-group': 'article',
          'x-label': L('Share links', 'Paylaşım bağlantıları'),
        },
      },
    },
    list: {
      type: 'object',
      'x-group': 'list',
      properties: {
        ...listLike('list'),
        showSummary: bool('list', 'Summaries', 'Özetler', false),
        showCards: bool('list', 'Cards', 'Kartlar', false),
        orderByWeight: bool('list', 'Order by weight', 'Ağırlığa göre sırala', false),
        groupByYear: bool('list', 'Group by year', 'Yıla göre grupla', true),
      },
    },
    taxonomy: {
      type: 'object',
      'x-group': 'taxonomy',
      properties: { ...listLike('taxonomy'), showTermCount: bool('taxonomy', 'Show term counts', 'Terim sayılarını göster', true) },
    },
    term: {
      type: 'object',
      'x-group': 'term',
      properties: { ...listLike('term'), groupByYear: bool('term', 'Group by year', 'Yıla göre grupla', false) },
    },
    verification: {
      type: 'object',
      'x-group': 'analytics',
      properties: {
        google: text('analytics', 'Google verification', 'Google doğrulama'),
        bing: text('analytics', 'Bing verification', 'Bing doğrulama'),
        pinterest: text('analytics', 'Pinterest verification', 'Pinterest doğrulama'),
        yandex: text('analytics', 'Yandex verification', 'Yandex doğrulama'),
        fediverse: text('analytics', 'Fediverse creator', 'Fediverse yazarı'),
      },
    },
    fathomAnalytics: {
      type: 'object',
      'x-group': 'analytics',
      properties: {
        site: text('analytics', 'Fathom site id', 'Fathom site kimliği'),
        domain: text('analytics', 'Fathom custom domain', 'Fathom özel alan adı'),
      },
    },
    umamiAnalytics: {
      type: 'object',
      'x-group': 'analytics',
      properties: {
        websiteid: text('analytics', 'Umami website id', 'Umami site kimliği'),
        domain: text('analytics', 'Umami domain', 'Umami alan adı'),
      },
    },
  },
  'x-pageParams': {
    showTableOfContents: { type: 'boolean', 'x-label': L('Table of contents', 'İçindekiler') },
    showHero: { type: 'boolean', 'x-label': L('Hero image', 'Büyük görsel') },
    heroStyle: { type: 'string', enum: HERO_STYLES, 'x-label': L('Hero style', 'Büyük görsel stili') },
    showReadingTime: { type: 'boolean', 'x-label': L('Reading time', 'Okuma süresi') },
    showAuthor: { type: 'boolean', 'x-label': L('Author', 'Yazar') },
    sharingLinks: { type: 'array', 'x-label': L('Share links', 'Paylaşım bağlantıları') },
    externalUrl: { type: 'string', format: 'uri', 'x-label': L('External address', 'Dış adres') },
    featureimage: { type: 'string', format: 'image', 'x-label': L('Feature image (URL)', 'Öne çıkan görsel (URL)') },
  },
  'x-features': {
    search: {
      label: L('Site search', 'Site içi arama'),
      description: L('Turns search on and adds the JSON index to the home page outputs.', 'Aramayı açar ve ana sayfa çıktılarına JSON dizinini ekler.'),
      steps: [
        { op: 'setParam', key: 'enableSearch', value: true },
        { op: 'ensureListContains', path: ['outputs', 'home'], value: 'JSON', defaultList: ['HTML', 'RSS'] },
      ],
    },
  },
}
